// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ErrorResponseErrorCode.
const (
	INTERNALERROR   ErrorResponseErrorCode = "INTERNAL_ERROR"
	NOCANDIDATE     ErrorResponseErrorCode = "NO_CANDIDATE"
	NOTASSIGNED     ErrorResponseErrorCode = "NOT_ASSIGNED"
	NOTFOUND        ErrorResponseErrorCode = "NOT_FOUND"
	PREXISTS        ErrorResponseErrorCode = "PR_EXISTS"
	PRMERGED        ErrorResponseErrorCode = "PR_MERGED"
	TEAMEXISTS      ErrorResponseErrorCode = "TEAM_EXISTS"
	USERNOTACTIVE   ErrorResponseErrorCode = "USER_NOT_ACTIVE"
	VALIDATIONERROR ErrorResponseErrorCode = "VALIDATION_ERROR"
)

// Defines values for PullRequestStatus.
const (
	PullRequestStatusMERGED PullRequestStatus = "MERGED"
	PullRequestStatusOPEN   PullRequestStatus = "OPEN"
)

// Defines values for PullRequestShortStatus.
const (
	PullRequestShortStatusMERGED PullRequestShortStatus = "MERGED"
	PullRequestShortStatusOPEN   PullRequestShortStatus = "OPEN"
)

// CountResponse defines model for CountResponse.
type CountResponse struct {
	Count int `json:"count"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error struct {
		Code    ErrorResponseErrorCode `json:"code"`
		Message string                 `json:"message"`
	} `json:"error"`
}

// ErrorResponseErrorCode defines model for ErrorResponse.Error.Code.
type ErrorResponseErrorCode string

// PullRequest defines model for PullRequest.
type PullRequest struct {
	// AssignedReviewers user_id назначенных ревьюверов (0..2)
	AssignedReviewers []string          `json:"assigned_reviewers"`
	AuthorId          string            `json:"author_id"`
	CreatedAt         *time.Time        `json:"createdAt"`
	MergedAt          *time.Time        `json:"mergedAt"`
	PullRequestId     string            `json:"pull_request_id"`
	PullRequestName   string            `json:"pull_request_name"`
	Status            PullRequestStatus `json:"status"`
}

// PullRequestStatus defines model for PullRequest.Status.
type PullRequestStatus string

// PullRequestCreateRequest defines model for PullRequestCreateRequest.
type PullRequestCreateRequest struct {
	AuthorId        string `json:"author_id"`
	PullRequestName string `json:"pull_request_name"`
}

// PullRequestShort defines model for PullRequestShort.
type PullRequestShort struct {
	AuthorId        string                 `json:"author_id"`
	PullRequestId   string                 `json:"pull_request_id"`
	PullRequestName string                 `json:"pull_request_name"`
	Status          PullRequestShortStatus `json:"status"`
}

// PullRequestShortStatus defines model for PullRequestShort.Status.
type PullRequestShortStatus string

// StatItem defines model for StatItem.
type StatItem struct {
	ReviewCount *int64  `json:"review_count,omitempty"`
	UserId      *string `json:"user_id,omitempty"`
}

// StatsResponse defines model for StatsResponse.
type StatsResponse struct {
	ReviewStats *[]StatItem `json:"review_stats,omitempty"`
}

// Team defines model for Team.
type Team struct {
	Members  []TeamMember `json:"members"`
	TeamName string       `json:"team_name"`
}

// TeamDeactivateRequest defines model for TeamDeactivateRequest.
type TeamDeactivateRequest struct {
	TeamName string `json:"team_name"`
}

// TeamDeactivateResponse defines model for TeamDeactivateResponse.
type TeamDeactivateResponse struct {
	DeactivatedUsersCount  *int `json:"deactivated_users_count,omitempty"`
	ReassignedReviewsCount *int `json:"reassigned_reviews_count,omitempty"`
}

// TeamMember defines model for TeamMember.
type TeamMember struct {
	IsActive bool   `json:"is_active"`
	UserId   string `json:"user_id"`
	Username string `json:"username"`
}

// User defines model for User.
type User struct {
	IsActive bool   `json:"is_active"`
	TeamName string `json:"team_name"`
	UserId   string `json:"user_id"`
	Username string `json:"username"`
}

// UserAddRequest defines model for UserAddRequest.
type UserAddRequest struct {
	IsActive bool   `json:"is_active"`
	TeamName string `json:"team_name"`
	Username string `json:"username"`
}

// PullRequestIdParam defines model for PullRequestIdParam.
type PullRequestIdParam = string

// TeamNameParam defines model for TeamNameParam.
type TeamNameParam = string

// TeamNameQuery defines model for TeamNameQuery.
type TeamNameQuery = string

// UserIdParam defines model for UserIdParam.
type UserIdParam = string

// UserIdQuery defines model for UserIdQuery.
type UserIdQuery = string

// PostPullRequestAssignJSONBody defines parameters for PostPullRequestAssign.
type PostPullRequestAssignJSONBody struct {
	PullRequestId string `json:"pull_request_id"`
	UserId        string `json:"user_id"`
}

// PostPullRequestMergeJSONBody defines parameters for PostPullRequestMerge.
type PostPullRequestMergeJSONBody struct {
	PullRequestId string `json:"pull_request_id"`
}

// PostPullRequestReassignJSONBody defines parameters for PostPullRequestReassign.
type PostPullRequestReassignJSONBody struct {
	OldUserId     string `json:"old_user_id"`
	PullRequestId string `json:"pull_request_id"`
}

// PostTeamEditJSONBody defines parameters for PostTeamEdit.
type PostTeamEditJSONBody struct {
	NewTeamName string `json:"new_team_name"`
	OldTeamName string `json:"old_team_name"`
}

// GetTeamGetParams defines parameters for GetTeamGet.
type GetTeamGetParams struct {
	// TeamName Уникальное имя команды
	TeamName TeamNameQuery `form:"team_name" json:"team_name"`
}

// GetUsersGetReviewParams defines parameters for GetUsersGetReview.
type GetUsersGetReviewParams struct {
	// UserId Идентификатор пользователя
	UserId UserIdQuery `form:"user_id" json:"user_id"`
}

// PostUsersMoveToTeamJSONBody defines parameters for PostUsersMoveToTeam.
type PostUsersMoveToTeamJSONBody struct {
	NewTeamName string `json:"new_team_name"`
	UserId      string `json:"user_id"`
}

// PostUsersSetIsActiveJSONBody defines parameters for PostUsersSetIsActive.
type PostUsersSetIsActiveJSONBody struct {
	IsActive bool   `json:"is_active"`
	UserId   string `json:"user_id"`
}

// PostPullRequestAssignJSONRequestBody defines body for PostPullRequestAssign for application/json ContentType.
type PostPullRequestAssignJSONRequestBody PostPullRequestAssignJSONBody

// PostPullRequestCreateJSONRequestBody defines body for PostPullRequestCreate for application/json ContentType.
type PostPullRequestCreateJSONRequestBody = PullRequestCreateRequest

// PostPullRequestMergeJSONRequestBody defines body for PostPullRequestMerge for application/json ContentType.
type PostPullRequestMergeJSONRequestBody PostPullRequestMergeJSONBody

// PostPullRequestReassignJSONRequestBody defines body for PostPullRequestReassign for application/json ContentType.
type PostPullRequestReassignJSONRequestBody PostPullRequestReassignJSONBody

// PostTeamAddJSONRequestBody defines body for PostTeamAdd for application/json ContentType.
type PostTeamAddJSONRequestBody = Team

// PostTeamDeactivateJSONRequestBody defines body for PostTeamDeactivate for application/json ContentType.
type PostTeamDeactivateJSONRequestBody = TeamDeactivateRequest

// PostTeamEditJSONRequestBody defines body for PostTeamEdit for application/json ContentType.
type PostTeamEditJSONRequestBody PostTeamEditJSONBody

// PostUsersAddJSONRequestBody defines body for PostUsersAdd for application/json ContentType.
type PostUsersAddJSONRequestBody = UserAddRequest

// PostUsersEditJSONRequestBody defines body for PostUsersEdit for application/json ContentType.
type PostUsersEditJSONRequestBody = User

// PostUsersMoveToTeamJSONRequestBody defines body for PostUsersMoveToTeam for application/json ContentType.
type PostUsersMoveToTeamJSONRequestBody PostUsersMoveToTeamJSONBody

// PostUsersSetIsActiveJSONRequestBody defines body for PostUsersSetIsActive for application/json ContentType.
type PostUsersSetIsActiveJSONRequestBody PostUsersSetIsActiveJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Check service health
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// Назначить ревьювера на PR
	// (POST /pullRequest/assign)
	PostPullRequestAssign(w http.ResponseWriter, r *http.Request)
	// Создать PR и автоматически назначить до 2 ревьюверов из команды автора
	// (POST /pullRequest/create)
	PostPullRequestCreate(w http.ResponseWriter, r *http.Request)
	// Получить информацию о PR по ID
	// (GET /pullRequest/get/{pull_request_id})
	GetPullRequestGetPullRequestId(w http.ResponseWriter, r *http.Request, pullRequestId PullRequestIdParam)
	// Пометить PR как MERGED (идемпотентная операция)
	// (POST /pullRequest/merge)
	PostPullRequestMerge(w http.ResponseWriter, r *http.Request)
	// Получить список открытых PR без ревьюверов
	// (GET /pullRequest/open-without-reviewers)
	GetPullRequestOpenWithoutReviewers(w http.ResponseWriter, r *http.Request)
	// Переназначить конкретного ревьювера на другого из его команды
	// (POST /pullRequest/reassign)
	PostPullRequestReassign(w http.ResponseWriter, r *http.Request)
	// Получить статистику по ревью
	// (GET /stats)
	GetStats(w http.ResponseWriter, r *http.Request)
	// Получить количество закрытых PR у команды
	// (GET /stats/team/{team_name}/merged-review-count)
	GetStatsTeamTeamNameMergedReviewCount(w http.ResponseWriter, r *http.Request, teamName TeamNameParam)
	// Получить количество назначенных OPEN PR у команды
	// (GET /stats/team/{team_name}/open-review-count)
	GetStatsTeamTeamNameOpenReviewCount(w http.ResponseWriter, r *http.Request, teamName TeamNameParam)
	// Получить количество закрытых PR у пользователя
	// (GET /stats/user/{user_id}/merged-review-count)
	GetStatsUserUserIdMergedReviewCount(w http.ResponseWriter, r *http.Request, userId UserIdParam)
	// Получить количество назначенных OPEN PR у пользователя
	// (GET /stats/user/{user_id}/open-review-count)
	GetStatsUserUserIdOpenReviewCount(w http.ResponseWriter, r *http.Request, userId UserIdParam)
	// Создать команду с участниками (создаёт/обновляет пользователей)
	// (POST /team/add)
	PostTeamAdd(w http.ResponseWriter, r *http.Request)
	// Массово деактивировать команду и переназначить ревью
	// (POST /team/deactivate)
	PostTeamDeactivate(w http.ResponseWriter, r *http.Request)
	// Изменить имя команды
	// (POST /team/edit)
	PostTeamEdit(w http.ResponseWriter, r *http.Request)
	// Получить команду с участниками
	// (GET /team/get)
	GetTeamGet(w http.ResponseWriter, r *http.Request, params GetTeamGetParams)
	// Добавить пользователя
	// (POST /users/add)
	PostUsersAdd(w http.ResponseWriter, r *http.Request)
	// Изменить пользователя
	// (POST /users/edit)
	PostUsersEdit(w http.ResponseWriter, r *http.Request)
	// Получить пользователя по ID
	// (GET /users/get/{user_id})
	GetUsersGetUserId(w http.ResponseWriter, r *http.Request, userId UserIdParam)
	// Получить PR'ы, где пользователь назначен ревьювером
	// (GET /users/getReview)
	GetUsersGetReview(w http.ResponseWriter, r *http.Request, params GetUsersGetReviewParams)
	// Переместить пользователя в другую команду
	// (POST /users/moveToTeam)
	PostUsersMoveToTeam(w http.ResponseWriter, r *http.Request)
	// Установить флаг активности пользователя
	// (POST /users/setIsActive)
	PostUsersSetIsActive(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Check service health
// (GET /health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Назначить ревьювера на PR
// (POST /pullRequest/assign)
func (_ Unimplemented) PostPullRequestAssign(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Создать PR и автоматически назначить до 2 ревьюверов из команды автора
// (POST /pullRequest/create)
func (_ Unimplemented) PostPullRequestCreate(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получить информацию о PR по ID
// (GET /pullRequest/get/{pull_request_id})
func (_ Unimplemented) GetPullRequestGetPullRequestId(w http.ResponseWriter, r *http.Request, pullRequestId PullRequestIdParam) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Пометить PR как MERGED (идемпотентная операция)
// (POST /pullRequest/merge)
func (_ Unimplemented) PostPullRequestMerge(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получить список открытых PR без ревьюверов
// (GET /pullRequest/open-without-reviewers)
func (_ Unimplemented) GetPullRequestOpenWithoutReviewers(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Переназначить конкретного ревьювера на другого из его команды
// (POST /pullRequest/reassign)
func (_ Unimplemented) PostPullRequestReassign(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получить статистику по ревью
// (GET /stats)
func (_ Unimplemented) GetStats(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получить количество закрытых PR у команды
// (GET /stats/team/{team_name}/merged-review-count)
func (_ Unimplemented) GetStatsTeamTeamNameMergedReviewCount(w http.ResponseWriter, r *http.Request, teamName TeamNameParam) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получить количество назначенных OPEN PR у команды
// (GET /stats/team/{team_name}/open-review-count)
func (_ Unimplemented) GetStatsTeamTeamNameOpenReviewCount(w http.ResponseWriter, r *http.Request, teamName TeamNameParam) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получить количество закрытых PR у пользователя
// (GET /stats/user/{user_id}/merged-review-count)
func (_ Unimplemented) GetStatsUserUserIdMergedReviewCount(w http.ResponseWriter, r *http.Request, userId UserIdParam) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получить количество назначенных OPEN PR у пользователя
// (GET /stats/user/{user_id}/open-review-count)
func (_ Unimplemented) GetStatsUserUserIdOpenReviewCount(w http.ResponseWriter, r *http.Request, userId UserIdParam) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Создать команду с участниками (создаёт/обновляет пользователей)
// (POST /team/add)
func (_ Unimplemented) PostTeamAdd(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Массово деактивировать команду и переназначить ревью
// (POST /team/deactivate)
func (_ Unimplemented) PostTeamDeactivate(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Изменить имя команды
// (POST /team/edit)
func (_ Unimplemented) PostTeamEdit(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получить команду с участниками
// (GET /team/get)
func (_ Unimplemented) GetTeamGet(w http.ResponseWriter, r *http.Request, params GetTeamGetParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Добавить пользователя
// (POST /users/add)
func (_ Unimplemented) PostUsersAdd(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Изменить пользователя
// (POST /users/edit)
func (_ Unimplemented) PostUsersEdit(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получить пользователя по ID
// (GET /users/get/{user_id})
func (_ Unimplemented) GetUsersGetUserId(w http.ResponseWriter, r *http.Request, userId UserIdParam) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получить PR'ы, где пользователь назначен ревьювером
// (GET /users/getReview)
func (_ Unimplemented) GetUsersGetReview(w http.ResponseWriter, r *http.Request, params GetUsersGetReviewParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Переместить пользователя в другую команду
// (POST /users/moveToTeam)
func (_ Unimplemented) PostUsersMoveToTeam(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Установить флаг активности пользователя
// (POST /users/setIsActive)
func (_ Unimplemented) PostUsersSetIsActive(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostPullRequestAssign operation middleware
func (siw *ServerInterfaceWrapper) PostPullRequestAssign(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostPullRequestAssign(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostPullRequestCreate operation middleware
func (siw *ServerInterfaceWrapper) PostPullRequestCreate(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostPullRequestCreate(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPullRequestGetPullRequestId operation middleware
func (siw *ServerInterfaceWrapper) GetPullRequestGetPullRequestId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "pull_request_id" -------------
	var pullRequestId PullRequestIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "pull_request_id", chi.URLParam(r, "pull_request_id"), &pullRequestId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pull_request_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPullRequestGetPullRequestId(w, r, pullRequestId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostPullRequestMerge operation middleware
func (siw *ServerInterfaceWrapper) PostPullRequestMerge(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostPullRequestMerge(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPullRequestOpenWithoutReviewers operation middleware
func (siw *ServerInterfaceWrapper) GetPullRequestOpenWithoutReviewers(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPullRequestOpenWithoutReviewers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostPullRequestReassign operation middleware
func (siw *ServerInterfaceWrapper) PostPullRequestReassign(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostPullRequestReassign(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStats operation middleware
func (siw *ServerInterfaceWrapper) GetStats(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStats(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStatsTeamTeamNameMergedReviewCount operation middleware
func (siw *ServerInterfaceWrapper) GetStatsTeamTeamNameMergedReviewCount(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "team_name" -------------
	var teamName TeamNameParam

	err = runtime.BindStyledParameterWithOptions("simple", "team_name", chi.URLParam(r, "team_name"), &teamName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "team_name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStatsTeamTeamNameMergedReviewCount(w, r, teamName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStatsTeamTeamNameOpenReviewCount operation middleware
func (siw *ServerInterfaceWrapper) GetStatsTeamTeamNameOpenReviewCount(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "team_name" -------------
	var teamName TeamNameParam

	err = runtime.BindStyledParameterWithOptions("simple", "team_name", chi.URLParam(r, "team_name"), &teamName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "team_name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStatsTeamTeamNameOpenReviewCount(w, r, teamName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStatsUserUserIdMergedReviewCount operation middleware
func (siw *ServerInterfaceWrapper) GetStatsUserUserIdMergedReviewCount(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "user_id" -------------
	var userId UserIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", chi.URLParam(r, "user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStatsUserUserIdMergedReviewCount(w, r, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStatsUserUserIdOpenReviewCount operation middleware
func (siw *ServerInterfaceWrapper) GetStatsUserUserIdOpenReviewCount(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "user_id" -------------
	var userId UserIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", chi.URLParam(r, "user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStatsUserUserIdOpenReviewCount(w, r, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostTeamAdd operation middleware
func (siw *ServerInterfaceWrapper) PostTeamAdd(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostTeamAdd(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostTeamDeactivate operation middleware
func (siw *ServerInterfaceWrapper) PostTeamDeactivate(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostTeamDeactivate(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostTeamEdit operation middleware
func (siw *ServerInterfaceWrapper) PostTeamEdit(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostTeamEdit(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTeamGet operation middleware
func (siw *ServerInterfaceWrapper) GetTeamGet(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTeamGetParams

	// ------------- Required query parameter "team_name" -------------

	if paramValue := r.URL.Query().Get("team_name"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "team_name"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "team_name", r.URL.Query(), &params.TeamName)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "team_name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTeamGet(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostUsersAdd operation middleware
func (siw *ServerInterfaceWrapper) PostUsersAdd(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostUsersAdd(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostUsersEdit operation middleware
func (siw *ServerInterfaceWrapper) PostUsersEdit(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostUsersEdit(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUsersGetUserId operation middleware
func (siw *ServerInterfaceWrapper) GetUsersGetUserId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "user_id" -------------
	var userId UserIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", chi.URLParam(r, "user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUsersGetUserId(w, r, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUsersGetReview operation middleware
func (siw *ServerInterfaceWrapper) GetUsersGetReview(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUsersGetReviewParams

	// ------------- Required query parameter "user_id" -------------

	if paramValue := r.URL.Query().Get("user_id"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "user_id"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "user_id", r.URL.Query(), &params.UserId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUsersGetReview(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostUsersMoveToTeam operation middleware
func (siw *ServerInterfaceWrapper) PostUsersMoveToTeam(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostUsersMoveToTeam(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostUsersSetIsActive operation middleware
func (siw *ServerInterfaceWrapper) PostUsersSetIsActive(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostUsersSetIsActive(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/pullRequest/assign", wrapper.PostPullRequestAssign)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/pullRequest/create", wrapper.PostPullRequestCreate)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/pullRequest/get/{pull_request_id}", wrapper.GetPullRequestGetPullRequestId)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/pullRequest/merge", wrapper.PostPullRequestMerge)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/pullRequest/open-without-reviewers", wrapper.GetPullRequestOpenWithoutReviewers)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/pullRequest/reassign", wrapper.PostPullRequestReassign)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/stats", wrapper.GetStats)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/stats/team/{team_name}/merged-review-count", wrapper.GetStatsTeamTeamNameMergedReviewCount)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/stats/team/{team_name}/open-review-count", wrapper.GetStatsTeamTeamNameOpenReviewCount)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/stats/user/{user_id}/merged-review-count", wrapper.GetStatsUserUserIdMergedReviewCount)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/stats/user/{user_id}/open-review-count", wrapper.GetStatsUserUserIdOpenReviewCount)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/team/add", wrapper.PostTeamAdd)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/team/deactivate", wrapper.PostTeamDeactivate)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/team/edit", wrapper.PostTeamEdit)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/team/get", wrapper.GetTeamGet)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/users/add", wrapper.PostUsersAdd)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/users/edit", wrapper.PostUsersEdit)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users/get/{user_id}", wrapper.GetUsersGetUserId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users/getReview", wrapper.GetUsersGetReview)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/users/moveToTeam", wrapper.PostUsersMoveToTeam)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/users/setIsActive", wrapper.PostUsersSetIsActive)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xcbW8bx/H/Kov9/4E4wMmUZTtA9I6xFVdALKsUnRY1BOLEW0uXkHfM3dGJIRDQQ9q0",
	"VRA1QF8ERZM0yBegFbOiZZH6CrPfqJjdvSfeA48Pkuw2bxKR3NudnZ35zfxm57xL63azZVvM8ly6vEtb",
	"uqM3mccc8Wm93WhU2Gdt5nqrxjr+hN8azK07ZsszbYsuU/gOXkIPBvwA+vxL6MMZdPkBDPkewceJep5q",
	"1MThLd3boRq19CbDT+1Go+bIETXToBrFD6bDDLrsOW2mUbe+w5o6Lus9b+EjrueY1jbtdDRaZXpzTW+y",
	"LMl+hoGUB17zr2EAQ+gR6MM5PyZwBkM4hy4M4CU/ShfOY3qzJv6eTqzftpnzfB5ifSYmmlmuxy5zpjlG",
	"uIChEPUUhnAivu7Ba36crrW2y5zJj1LKlqWx6WUbUd00wnX8H4VL3LPblldhbsu2XCY8xrFbzPFMJn6u",
	"48+RWUzLY9vMEXsMl3yixm1q/jh76xNW92hHoyuOYzvRBdgXerPVkH/ib3IZA59ae1Stffjo8dp9qtEm",
	"c119G791mGu3nTojlu2Rp3bbMsTycUGDqUblN+RKVruJclZXyg9rK79f3ahuUI2uV2J/P1ypPFjBtVGO",
	"8sbG6oM19bF2r7x2f/V+ubqifvWl/Lj8EX69+mittlKpPKpQjT7eWKnUxAz3qqsf4wOra9WVylr5IzUk",
	"1JJ/JpHdphlTXNEGi2gnqfGR8VIvaQcTAcOk3nTXNbctZtQc9sxknyv8jJuxMj4CA+jCKf6Xf4VmDQN+",
	"xP9I+B704IR/zb+BE+jxPTRocmPx5s2ld9GaPdZ0U7YbCKo7jv4cP+ttb8cWVp42uu4w3WNGWezhqe00",
	"dY8uU0P32IJnCkix2o2GvoUGJz0jRffO9mwzjMJ+mqCxMdJ9U0a5nu613ajFPlpfWaMaVbaZtJ2R805G",
	"oOTCUZ0GS2ppZz7Gbu4J5WcbUe7JFVFI3uYSWxkj7MaO7cwm5Ft6sml62fB0b9VjzaQ+5OHXAuAPPMK0",
	"vPfuUC0RCbQgCqWeX+rSbnbEUeuj7OJzABT/77CndJn+XynM8EoqkJWC7STwI00CTGiSCzdZc0vhXKE1",
	"cZaH4pk01AqTmrFWHc1/fCE2M8S+z/S6Zz7L87qpVi6yXtaJGcEYo4am4NYyswZcfgRmckZnnZ3SekIQ",
	"060JSZiU6qnebngjmL1l2w2mW/lWK38rpsIwAwue0SKCpOkVc8MxwielzTvVS91L1DrH76tsGJmGOfMO",
	"i+9iQtlxCtN6aovJTQ8jPV2vkIqKg6QsTLbJLI9sMOeZWWfkRpW5Hqnq7qca+VBvNMjS4tJdTGyeMceV",
	"+dGtm4s3F1F2u8UsvWXSZXr75uLN24jcurcjdFLaYXrD28E/t5nQGWpMxwxr1aDL9AHzfiNH4CalB4oH",
	"lxYXkxmZL5zpEjmvBEC33WzqSETovR1W/5S4atiOP7Onb7uoOrXUJj5UaoWhsyR9Vhyp7aaIuW67XiTU",
	"Sn0pVsJc7wPbeC6zcctj0tf1Vqth1sUMpU9cW8wdcpa44RQJwrkxKD+M+o+m20WcWHXSj6HwxvICSjQh",
	"F0uPsMZ/xfPpRN6NarizeGdu8sSZW4pE6xXk+a+hn0Vbv0YZe1LQV5LzSiHfLyCk4okqNmOKLkQPbBm+",
	"l2vAKT+O66LLD+TSXSKTK7KOxOyZ3min0s4o9QtpZ123kHBK0ye2RaQQOJfQhWV75QDOImL9mKMK6MIZ",
	"sn48QRjkyZRkkaFkaLDo40I8KUInwutnPlf4Hrp8jx/yPws618cjfCkKOSG7gwu+B104QQNIMsA+Px5B",
	"HpwzGNIXB5QgiF15ZuKwfEiKOIWbAkyS/hUGJklYJgamSMkiQhdo+1ZqEr5My4ZBXKY79R1a+FQyaVUh",
	"FLo12S5aThbJf0LbS4iJtxEOE5uNsG2KAW/h1uLC0p3qraXl23eW7773Bxpl00ibUxgUbTkLtxYXC+gu",
	"JE2SK8VNfCRGOJPBayrWJ+CN78MQTuEldK8BXuFvcCLLgqVoHVW6SRxV+dHEuJoBhEE9LISb9QoxDaI3",
	"HKYbzwn7wkRXnCPcoJ4P4d/QI3yfH/K/QI/v8wM44YfQ4wejOPKTfyICQ0QIIghEqClUkSiqfoVzwBn+",
	"NEjgDmIZWUqvT0EfTkeq1sHsiFDFkWmbeaXdEePv5OV5kfnin1YF149cZDxJV3g4pJRy0dHZvMbU5Qd4",
	"wf8KPQx+In5eQ6KSTETidiXD9mFoJX0Y8C/FqaNV/Qn6/BsCQ2FxFzAkq/eL24LAxMJB6qEYPUOMyobc",
	"PAAdm2SPSaQvL32eQ+AKo1JW3JpPnFJ55NVHKjgRwUog55Afi7StT3xx3lB/O0eAV/6Gz5xhfuzn7Deg",
	"L548R3cTWfSAHwggPyYwhAuZMgrHPH63uC8iGV/43PR27La3ELvdKADMj1rM+p18thI8OiOuFio2JurY",
	"yUJnEnV/ggvoixTmTLKWXMDj+5HhQuNnfI8f8QOR7+PxvIAenKbGzeLq9+t/hdGw4j8wAyDajRAqFCgs",
	"5bp8jvviXHnltplxVIstcf2oehtR9W4qqs4zt8c9tBp6nRm1LbTP9l06PxAdmTznJhM5+xB+gWEKPaVj",
	"r2gcGl9pswB4w49i9l6SRCOCnvAjWVwR5YMBDP+nqzyiAsGPZYKGYWEfXkOPBNWb6Uo8PialFnnu6ZZh",
	"GqrIEJeLHwgugTGXH8KFXxk5UzytL1mKwsdM0Ua6C0LpLFtVd4gyKVGArvvyENMiHsPM3q9GKf+doB5F",
	"4AU/SingpIH8ef4mYh0T0eYNVUP361VKSOLZxNsxXaXp6yxeXWT5X7KIleaqii4gZxxgyBQ5zSATRGSN",
	"C16ijDhEDJO0syf/Hu2ZyomswS1pVu4iLlvpJTK/+G1uahbCDxQr3xelzzPc/kVMN+NTk9E5+GFijlBR",
	"ctMRDZXQT0q7wXVQRzIyQ+V/C8ENZK4aq0xv+r1wgqMZMgcULVQTU/R4s9+lsvN4j1faGf1DRBhVN+EH",
	"GAOvg6cLOXLKXNAdy9rPUnYCp6LuHktm0YCyHK2A/QgWMbX1II341XbeDttJb27DnHVyM8I8s7Srss3p",
	"QOixyxzZXDo7BEUbaH81Imt8sjRJ+XASIMpu+i1sS5MDUmhJs8LRr3Z01XY0HpQmMykR33TDyK/KYNgp",
	"G8YslZigye7JbtiyIYsJYYcPLTfMOqMdLTZmKT7mA3tLGFukbYi29OdN8eZHYTpRDQjUnG9YPdVjGN1w",
	"pAFKNqUV0UDeQwVUsqXXP2WqYz6rmOLLWkBRReoZ8UAcvULFGIyeuHiFnvg99NCH+J6gCmfIzfgRvJJY",
	"jDxwyPfJDeFR+KkvitJ7GkGvQccTJF4Vmedxxxp/AyEkysGhXeJN6+jRTHvrGkt5DgnfJwKxumIG/2Wg",
	"c+iTG+Hp82/5QQmG8EIV2V7zY1lBSUUq6MGraFEfzS8GVmHT6XjMCptYZ2hJG+ccyc7cK24fy2jXLZAq",
	"v4w1JvVlSV/6qxZh2JmVEr/74I3O9v8pzHNfFngz95xm3rLymVX4Sa1AJMyVGaY33lBXcNS8uiYt9nkt",
	"v6fWbhi1CbrF48O1kQWuu3syjOSJl+2SbyKKgpsqCV5PVb2IAReNNpcUHfYJP0AfwZhIZGAU6jqfJHB8",
	"F+g5aKtIfTE003MUh8miMjj+AZu+hCJf0ZyStUTCfCJNe2MSP21WB4o274yc21ta5CmQumSYpHi/ZTxT",
	"QkbsTkOViulp5E2LufGX4qtPRHqTXZTvvwFUfAIQ+7vIW8WFUXD1OIZdCwuIGc34FEA8M2MOUOzgri4s",
	"T2ws8cj8FlVuEpFuGiMRXaN+US8v7olH1f+naBC9spJd5vnHokqWqt7iul3GllKaR1OtQNZji1iAGjmd",
	"Bcwr/Yl2+8jlL7VZaHMkGyrY1+rOsd9uglfOwvcq48IU6g6KN/G9I7vU//v8Zb3yDj/SCPyCw3M7jQo1",
	"qmT7VtN+xqp28Ap4fjB+GA6+Olo+hV29WVR88pjvl1fOoYe52BsV91XvW4E3cNJ7hc5VbjkuLpwETUH8",
	"kH8zQlRyTdpl3qobvos4xqY3IqNnuMmJ0NOnesNlxRF5zHvgU5j/uHe759wu21Yv8CdVkEbAxxL3HFX5",
	"KxXwtiKx5IdI9f1beW0IrzLB9i2KJj/LDjG1OVWY/RJeQxd+IZE670C9IdGfKDvvBN/t+v/wlqwJdLTg",
	"Czk48kWsWy/yvXrHPvKNvIjtbHb+EwAA//9VuHCwvU4AAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
