// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ErrorResponseErrorCode.
const (
	INTERNALERROR   ErrorResponseErrorCode = "INTERNAL_ERROR"
	NOCANDIDATE     ErrorResponseErrorCode = "NO_CANDIDATE"
	NOTASSIGNED     ErrorResponseErrorCode = "NOT_ASSIGNED"
	NOTFOUND        ErrorResponseErrorCode = "NOT_FOUND"
	PREXISTS        ErrorResponseErrorCode = "PR_EXISTS"
	PRMERGED        ErrorResponseErrorCode = "PR_MERGED"
	TEAMEXISTS      ErrorResponseErrorCode = "TEAM_EXISTS"
	VALIDATIONERROR ErrorResponseErrorCode = "VALIDATION_ERROR"
)

// Defines values for PullRequestStatus.
const (
	PullRequestStatusMERGED PullRequestStatus = "MERGED"
	PullRequestStatusOPEN   PullRequestStatus = "OPEN"
)

// Defines values for PullRequestShortStatus.
const (
	PullRequestShortStatusMERGED PullRequestShortStatus = "MERGED"
	PullRequestShortStatusOPEN   PullRequestShortStatus = "OPEN"
)

// CountResponse defines model for CountResponse.
type CountResponse struct {
	Count int `json:"count"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error struct {
		Code    ErrorResponseErrorCode `json:"code"`
		Message string                 `json:"message"`
	} `json:"error"`
}

// ErrorResponseErrorCode defines model for ErrorResponse.Error.Code.
type ErrorResponseErrorCode string

// PullRequest defines model for PullRequest.
type PullRequest struct {
	// AssignedReviewers user_id назначенных ревьюверов (0..2)
	AssignedReviewers []string          `json:"assigned_reviewers"`
	AuthorId          string            `json:"author_id"`
	CreatedAt         *time.Time        `json:"createdAt"`
	MergedAt          *time.Time        `json:"mergedAt"`
	PullRequestId     string            `json:"pull_request_id"`
	PullRequestName   string            `json:"pull_request_name"`
	Status            PullRequestStatus `json:"status"`
}

// PullRequestStatus defines model for PullRequest.Status.
type PullRequestStatus string

// PullRequestCreateRequest defines model for PullRequestCreateRequest.
type PullRequestCreateRequest struct {
	AuthorId        string `json:"author_id"`
	PullRequestName string `json:"pull_request_name"`
}

// PullRequestShort defines model for PullRequestShort.
type PullRequestShort struct {
	AuthorId        string                 `json:"author_id"`
	PullRequestId   string                 `json:"pull_request_id"`
	PullRequestName string                 `json:"pull_request_name"`
	Status          PullRequestShortStatus `json:"status"`
}

// PullRequestShortStatus defines model for PullRequestShort.Status.
type PullRequestShortStatus string

// StatItem defines model for StatItem.
type StatItem struct {
	ReviewCount *int64  `json:"review_count,omitempty"`
	UserId      *string `json:"user_id,omitempty"`
}

// StatsResponse defines model for StatsResponse.
type StatsResponse struct {
	ReviewStats *[]StatItem `json:"review_stats,omitempty"`
}

// Team defines model for Team.
type Team struct {
	Members  []TeamMember `json:"members"`
	TeamName string       `json:"team_name"`
}

// TeamDeactivateRequest defines model for TeamDeactivateRequest.
type TeamDeactivateRequest struct {
	TeamName string `json:"team_name"`
}

// TeamDeactivateResponse defines model for TeamDeactivateResponse.
type TeamDeactivateResponse struct {
	DeactivatedUsersCount  *int `json:"deactivated_users_count,omitempty"`
	ReassignedReviewsCount *int `json:"reassigned_reviews_count,omitempty"`
}

// TeamMember defines model for TeamMember.
type TeamMember struct {
	IsActive bool   `json:"is_active"`
	UserId   string `json:"user_id"`
	Username string `json:"username"`
}

// User defines model for User.
type User struct {
	IsActive bool   `json:"is_active"`
	TeamName string `json:"team_name"`
	UserId   string `json:"user_id"`
	Username string `json:"username"`
}

// UserAddRequest defines model for UserAddRequest.
type UserAddRequest struct {
	IsActive bool   `json:"is_active"`
	TeamName string `json:"team_name"`
	Username string `json:"username"`
}

// PullRequestIdParam defines model for PullRequestIdParam.
type PullRequestIdParam = string

// TeamNameParam defines model for TeamNameParam.
type TeamNameParam = string

// TeamNameQuery defines model for TeamNameQuery.
type TeamNameQuery = string

// UserIdParam defines model for UserIdParam.
type UserIdParam = string

// UserIdQuery defines model for UserIdQuery.
type UserIdQuery = string

// PostPullRequestMergeJSONBody defines parameters for PostPullRequestMerge.
type PostPullRequestMergeJSONBody struct {
	PullRequestId string `json:"pull_request_id"`
}

// PostPullRequestReassignJSONBody defines parameters for PostPullRequestReassign.
type PostPullRequestReassignJSONBody struct {
	OldUserId     string `json:"old_user_id"`
	PullRequestId string `json:"pull_request_id"`
}

// PostTeamEditJSONBody defines parameters for PostTeamEdit.
type PostTeamEditJSONBody struct {
	NewTeamName string `json:"new_team_name"`
	OldTeamName string `json:"old_team_name"`
}

// GetTeamGetParams defines parameters for GetTeamGet.
type GetTeamGetParams struct {
	// TeamName Уникальное имя команды
	TeamName TeamNameQuery `form:"team_name" json:"team_name"`
}

// GetUsersGetReviewParams defines parameters for GetUsersGetReview.
type GetUsersGetReviewParams struct {
	// UserId Идентификатор пользователя
	UserId UserIdQuery `form:"user_id" json:"user_id"`
}

// PostUsersMoveToTeamJSONBody defines parameters for PostUsersMoveToTeam.
type PostUsersMoveToTeamJSONBody struct {
	NewTeamName string `json:"new_team_name"`
	UserId      string `json:"user_id"`
}

// PostUsersSetIsActiveJSONBody defines parameters for PostUsersSetIsActive.
type PostUsersSetIsActiveJSONBody struct {
	IsActive bool   `json:"is_active"`
	UserId   string `json:"user_id"`
}

// PostPullRequestCreateJSONRequestBody defines body for PostPullRequestCreate for application/json ContentType.
type PostPullRequestCreateJSONRequestBody = PullRequestCreateRequest

// PostPullRequestMergeJSONRequestBody defines body for PostPullRequestMerge for application/json ContentType.
type PostPullRequestMergeJSONRequestBody PostPullRequestMergeJSONBody

// PostPullRequestReassignJSONRequestBody defines body for PostPullRequestReassign for application/json ContentType.
type PostPullRequestReassignJSONRequestBody PostPullRequestReassignJSONBody

// PostTeamAddJSONRequestBody defines body for PostTeamAdd for application/json ContentType.
type PostTeamAddJSONRequestBody = Team

// PostTeamDeactivateJSONRequestBody defines body for PostTeamDeactivate for application/json ContentType.
type PostTeamDeactivateJSONRequestBody = TeamDeactivateRequest

// PostTeamEditJSONRequestBody defines body for PostTeamEdit for application/json ContentType.
type PostTeamEditJSONRequestBody PostTeamEditJSONBody

// PostUsersAddJSONRequestBody defines body for PostUsersAdd for application/json ContentType.
type PostUsersAddJSONRequestBody = UserAddRequest

// PostUsersEditJSONRequestBody defines body for PostUsersEdit for application/json ContentType.
type PostUsersEditJSONRequestBody = User

// PostUsersMoveToTeamJSONRequestBody defines body for PostUsersMoveToTeam for application/json ContentType.
type PostUsersMoveToTeamJSONRequestBody PostUsersMoveToTeamJSONBody

// PostUsersSetIsActiveJSONRequestBody defines body for PostUsersSetIsActive for application/json ContentType.
type PostUsersSetIsActiveJSONRequestBody PostUsersSetIsActiveJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Check service health
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// Создать PR и автоматически назначить до 2 ревьюверов из команды автора
	// (POST /pullRequest/create)
	PostPullRequestCreate(w http.ResponseWriter, r *http.Request)
	// Получить информацию о PR по ID
	// (GET /pullRequest/get/{pull_request_id})
	GetPullRequestGetPullRequestId(w http.ResponseWriter, r *http.Request, pullRequestId PullRequestIdParam)
	// Пометить PR как MERGED (идемпотентная операция)
	// (POST /pullRequest/merge)
	PostPullRequestMerge(w http.ResponseWriter, r *http.Request)
	// Получить список открытых PR без ревьюверов
	// (GET /pullRequest/open-without-reviewers)
	GetPullRequestOpenWithoutReviewers(w http.ResponseWriter, r *http.Request)
	// Переназначить конкретного ревьювера на другого из его команды
	// (POST /pullRequest/reassign)
	PostPullRequestReassign(w http.ResponseWriter, r *http.Request)
	// Получить статистику по ревью
	// (GET /stats)
	GetStats(w http.ResponseWriter, r *http.Request)
	// Получить количество закрытых PR у команды
	// (GET /stats/team/{team_name}/merged-review-count)
	GetStatsTeamTeamNameMergedReviewCount(w http.ResponseWriter, r *http.Request, teamName TeamNameParam)
	// Получить количество назначенных OPEN PR у команды
	// (GET /stats/team/{team_name}/open-review-count)
	GetStatsTeamTeamNameOpenReviewCount(w http.ResponseWriter, r *http.Request, teamName TeamNameParam)
	// Получить количество закрытых PR у пользователя
	// (GET /stats/user/{user_id}/merged-review-count)
	GetStatsUserUserIdMergedReviewCount(w http.ResponseWriter, r *http.Request, userId UserIdParam)
	// Получить количество назначенных OPEN PR у пользователя
	// (GET /stats/user/{user_id}/open-review-count)
	GetStatsUserUserIdOpenReviewCount(w http.ResponseWriter, r *http.Request, userId UserIdParam)
	// Создать команду с участниками (создаёт/обновляет пользователей)
	// (POST /team/add)
	PostTeamAdd(w http.ResponseWriter, r *http.Request)
	// Массово деактивировать команду и переназначить ревью
	// (POST /team/deactivate)
	PostTeamDeactivate(w http.ResponseWriter, r *http.Request)
	// Изменить имя команды
	// (POST /team/edit)
	PostTeamEdit(w http.ResponseWriter, r *http.Request)
	// Получить команду с участниками
	// (GET /team/get)
	GetTeamGet(w http.ResponseWriter, r *http.Request, params GetTeamGetParams)
	// Добавить пользователя
	// (POST /users/add)
	PostUsersAdd(w http.ResponseWriter, r *http.Request)
	// Изменить пользователя
	// (POST /users/edit)
	PostUsersEdit(w http.ResponseWriter, r *http.Request)
	// Получить PR'ы, где пользователь назначен ревьювером
	// (GET /users/getReview)
	GetUsersGetReview(w http.ResponseWriter, r *http.Request, params GetUsersGetReviewParams)
	// Переместить пользователя в другую команду
	// (POST /users/moveToTeam)
	PostUsersMoveToTeam(w http.ResponseWriter, r *http.Request)
	// Установить флаг активности пользователя
	// (POST /users/setIsActive)
	PostUsersSetIsActive(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Check service health
// (GET /health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Создать PR и автоматически назначить до 2 ревьюверов из команды автора
// (POST /pullRequest/create)
func (_ Unimplemented) PostPullRequestCreate(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получить информацию о PR по ID
// (GET /pullRequest/get/{pull_request_id})
func (_ Unimplemented) GetPullRequestGetPullRequestId(w http.ResponseWriter, r *http.Request, pullRequestId PullRequestIdParam) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Пометить PR как MERGED (идемпотентная операция)
// (POST /pullRequest/merge)
func (_ Unimplemented) PostPullRequestMerge(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получить список открытых PR без ревьюверов
// (GET /pullRequest/open-without-reviewers)
func (_ Unimplemented) GetPullRequestOpenWithoutReviewers(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Переназначить конкретного ревьювера на другого из его команды
// (POST /pullRequest/reassign)
func (_ Unimplemented) PostPullRequestReassign(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получить статистику по ревью
// (GET /stats)
func (_ Unimplemented) GetStats(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получить количество закрытых PR у команды
// (GET /stats/team/{team_name}/merged-review-count)
func (_ Unimplemented) GetStatsTeamTeamNameMergedReviewCount(w http.ResponseWriter, r *http.Request, teamName TeamNameParam) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получить количество назначенных OPEN PR у команды
// (GET /stats/team/{team_name}/open-review-count)
func (_ Unimplemented) GetStatsTeamTeamNameOpenReviewCount(w http.ResponseWriter, r *http.Request, teamName TeamNameParam) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получить количество закрытых PR у пользователя
// (GET /stats/user/{user_id}/merged-review-count)
func (_ Unimplemented) GetStatsUserUserIdMergedReviewCount(w http.ResponseWriter, r *http.Request, userId UserIdParam) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получить количество назначенных OPEN PR у пользователя
// (GET /stats/user/{user_id}/open-review-count)
func (_ Unimplemented) GetStatsUserUserIdOpenReviewCount(w http.ResponseWriter, r *http.Request, userId UserIdParam) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Создать команду с участниками (создаёт/обновляет пользователей)
// (POST /team/add)
func (_ Unimplemented) PostTeamAdd(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Массово деактивировать команду и переназначить ревью
// (POST /team/deactivate)
func (_ Unimplemented) PostTeamDeactivate(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Изменить имя команды
// (POST /team/edit)
func (_ Unimplemented) PostTeamEdit(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получить команду с участниками
// (GET /team/get)
func (_ Unimplemented) GetTeamGet(w http.ResponseWriter, r *http.Request, params GetTeamGetParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Добавить пользователя
// (POST /users/add)
func (_ Unimplemented) PostUsersAdd(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Изменить пользователя
// (POST /users/edit)
func (_ Unimplemented) PostUsersEdit(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получить PR'ы, где пользователь назначен ревьювером
// (GET /users/getReview)
func (_ Unimplemented) GetUsersGetReview(w http.ResponseWriter, r *http.Request, params GetUsersGetReviewParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Переместить пользователя в другую команду
// (POST /users/moveToTeam)
func (_ Unimplemented) PostUsersMoveToTeam(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Установить флаг активности пользователя
// (POST /users/setIsActive)
func (_ Unimplemented) PostUsersSetIsActive(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostPullRequestCreate operation middleware
func (siw *ServerInterfaceWrapper) PostPullRequestCreate(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostPullRequestCreate(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPullRequestGetPullRequestId operation middleware
func (siw *ServerInterfaceWrapper) GetPullRequestGetPullRequestId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "pull_request_id" -------------
	var pullRequestId PullRequestIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "pull_request_id", chi.URLParam(r, "pull_request_id"), &pullRequestId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pull_request_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPullRequestGetPullRequestId(w, r, pullRequestId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostPullRequestMerge operation middleware
func (siw *ServerInterfaceWrapper) PostPullRequestMerge(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostPullRequestMerge(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPullRequestOpenWithoutReviewers operation middleware
func (siw *ServerInterfaceWrapper) GetPullRequestOpenWithoutReviewers(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPullRequestOpenWithoutReviewers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostPullRequestReassign operation middleware
func (siw *ServerInterfaceWrapper) PostPullRequestReassign(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostPullRequestReassign(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStats operation middleware
func (siw *ServerInterfaceWrapper) GetStats(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStats(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStatsTeamTeamNameMergedReviewCount operation middleware
func (siw *ServerInterfaceWrapper) GetStatsTeamTeamNameMergedReviewCount(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "team_name" -------------
	var teamName TeamNameParam

	err = runtime.BindStyledParameterWithOptions("simple", "team_name", chi.URLParam(r, "team_name"), &teamName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "team_name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStatsTeamTeamNameMergedReviewCount(w, r, teamName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStatsTeamTeamNameOpenReviewCount operation middleware
func (siw *ServerInterfaceWrapper) GetStatsTeamTeamNameOpenReviewCount(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "team_name" -------------
	var teamName TeamNameParam

	err = runtime.BindStyledParameterWithOptions("simple", "team_name", chi.URLParam(r, "team_name"), &teamName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "team_name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStatsTeamTeamNameOpenReviewCount(w, r, teamName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStatsUserUserIdMergedReviewCount operation middleware
func (siw *ServerInterfaceWrapper) GetStatsUserUserIdMergedReviewCount(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "user_id" -------------
	var userId UserIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", chi.URLParam(r, "user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStatsUserUserIdMergedReviewCount(w, r, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStatsUserUserIdOpenReviewCount operation middleware
func (siw *ServerInterfaceWrapper) GetStatsUserUserIdOpenReviewCount(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "user_id" -------------
	var userId UserIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", chi.URLParam(r, "user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStatsUserUserIdOpenReviewCount(w, r, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostTeamAdd operation middleware
func (siw *ServerInterfaceWrapper) PostTeamAdd(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostTeamAdd(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostTeamDeactivate operation middleware
func (siw *ServerInterfaceWrapper) PostTeamDeactivate(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostTeamDeactivate(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostTeamEdit operation middleware
func (siw *ServerInterfaceWrapper) PostTeamEdit(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostTeamEdit(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTeamGet operation middleware
func (siw *ServerInterfaceWrapper) GetTeamGet(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTeamGetParams

	// ------------- Required query parameter "team_name" -------------

	if paramValue := r.URL.Query().Get("team_name"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "team_name"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "team_name", r.URL.Query(), &params.TeamName)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "team_name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTeamGet(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostUsersAdd operation middleware
func (siw *ServerInterfaceWrapper) PostUsersAdd(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostUsersAdd(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostUsersEdit operation middleware
func (siw *ServerInterfaceWrapper) PostUsersEdit(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostUsersEdit(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUsersGetReview operation middleware
func (siw *ServerInterfaceWrapper) GetUsersGetReview(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUsersGetReviewParams

	// ------------- Required query parameter "user_id" -------------

	if paramValue := r.URL.Query().Get("user_id"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "user_id"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "user_id", r.URL.Query(), &params.UserId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUsersGetReview(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostUsersMoveToTeam operation middleware
func (siw *ServerInterfaceWrapper) PostUsersMoveToTeam(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostUsersMoveToTeam(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostUsersSetIsActive operation middleware
func (siw *ServerInterfaceWrapper) PostUsersSetIsActive(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostUsersSetIsActive(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/pullRequest/create", wrapper.PostPullRequestCreate)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/pullRequest/get/{pull_request_id}", wrapper.GetPullRequestGetPullRequestId)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/pullRequest/merge", wrapper.PostPullRequestMerge)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/pullRequest/open-without-reviewers", wrapper.GetPullRequestOpenWithoutReviewers)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/pullRequest/reassign", wrapper.PostPullRequestReassign)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/stats", wrapper.GetStats)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/stats/team/{team_name}/merged-review-count", wrapper.GetStatsTeamTeamNameMergedReviewCount)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/stats/team/{team_name}/open-review-count", wrapper.GetStatsTeamTeamNameOpenReviewCount)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/stats/user/{user_id}/merged-review-count", wrapper.GetStatsUserUserIdMergedReviewCount)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/stats/user/{user_id}/open-review-count", wrapper.GetStatsUserUserIdOpenReviewCount)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/team/add", wrapper.PostTeamAdd)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/team/deactivate", wrapper.PostTeamDeactivate)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/team/edit", wrapper.PostTeamEdit)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/team/get", wrapper.GetTeamGet)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/users/add", wrapper.PostUsersAdd)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/users/edit", wrapper.PostUsersEdit)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users/getReview", wrapper.GetUsersGetReview)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/users/moveToTeam", wrapper.PostUsersMoveToTeam)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/users/setIsActive", wrapper.PostUsersSetIsActive)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xcbW8bx/H/Kov9/4E4AGXSsh0gesfYiisgllVKaYsaAnHiraVLyDvmbunEEAhIVNq0",
	"lRE1QF8ERZMgyBegFbOi9UB/hdlvVMzu8p7veCQl2QbyxhDv9m5nZ2d+M7/ZOe/ShtNqOzazuUeXdmnb",
	"cI0W48yVv9Y6zWaNfdFhHl8x1/AWXjWZ13CtNrccmy5R+B5ewgAuRA+G4msYwin0RQ9GYo/g40Q/T0vU",
	"wuFtg+/QErWNFsNfnWaz7qoRdcukJYo/LJeZdIm7HVaiXmOHtQyclj9r4yMedy17m3a7JbrBjNaq0WJZ",
	"kv0CF0oeOBPP4QJGMCAwhHNxROAURnAOfbiAl+IwXTjOjFZd/j2bWL/vMPfZZYj1hXzR3HJ96jF3lm2E",
	"1zCSop7ACI7l5QGciaN0rXU85k6/lUq2LI3NLltMdbMI1x3flC5xz+nYvMa8tmN7THqM67SZyy0mbzfw",
	"dugtls3ZNnPlGoMpH+txm6XxOGfrM9bgtFuiy67ruOEJ2FdGq91Uf+I9NY2JT60+2qh//OjT1fu0RFvM",
	"84xtvOoyz+m4DUZsh5MnTsc25fRRQf1XxeU31Ux2p4VybixXH9aX/7SyvrFOS3StFvn74XLtwTLOjXJU",
	"19dXHqzqn/V71dX7K/erG8v67ljKP1Q/wcsrj1bry7Xaoxot0ZXVjeXaavUTfSHQyXgHQmtLM52oWk0W",
	"0kVSv7HxSgtp2xCCvqSWDM+ztm1m1l321GJfarSMGq02NQIX0IcT/Fd8g0YMF+JQ/IWIPRjAsXguvoVj",
	"GIg9NF9yo3Lz5uL7aLuctbyU5fqCGq5rPMPfRofvONKm00Y3XGZwZlblGp44bsvgdImaBmcL3JIAYnea",
	"TWMLzUv5QYru3e353hAH+TRBI2OUs6aM8rjBO17YPh+tLa/SEtWWmLSd2H4n401y4rBO/SlLaXs+wW7u",
	"SeVnG1HuzhVRSN7iEkuZIOz6juPOJ+Q7urNpelnnBl/hrJXUh9r8ug/zvkdYNv/gDi0lcL/kx5zU/Uud",
	"2suOL3p+lF3+9oHi/132hC7R/ysH+VxZh62yv5wEfqRJgOlLcuIWa21pnCs0J77loXwmDbWCFGaiVYez",
	"nbEQmxli32dGg1tP87xuppmLzJe1Y6Y/xqyjKXj1zBwBp4/BTM7orL3TWk8IYnl1KQlTUj0xOk0ew+wt",
	"x2kyw863WnWvmAqDfMt/phQSJE2vmAlOED4pbd6uXulawtY5eV1V08w0zLlXWHwVU8qOr7DsJ458ucUx",
	"0tO1GqnpOEiq0mRbzOZknblPrQYjNzaYx8mG4X1eIh8bzSZZrCzexcTmKXM9lR/dulm5WUHZnTazjbZF",
	"l+jtm5WbtxG5Db4jdVLeYUaT7+Cf20zqDDVmYIa1YtIl+oDx36kRuEjlgfLBxUolmZGNhbM8ot6rANDr",
	"tFoG0g56b4c1PieeHrYzfjM3tj1UnZ5qEx8qt4PQWVZZltxSx0sRc83xeCIv0ByEefwjx3ymcm+bM+Xr",
	"RrvdtBryDeXPPJQ+wgNCUZl2bqXGuiVaNU3iMcNt7NBumN/koXZm9tKN2hGiRjeh81vTraLtZuXSj2ln",
	"Ef3sNlpj/mLl5ba7cKtSKaCIINFQ+UU3opmoQyrxCmorDY7xUtQC12pE7MMITuAlcnzclzuVOwW0Vmz3",
	"otQxZX74Jxwr4lwOVxqgjyxloKjKK821D5V0H063p3GGGmaMAUNdqxHLJEbTZYb5jLCvLI97sb2Ya52o",
	"5wP4LwyI2BcH4u8wEPuiB8fiAAaiF/N6+Hm8I6InnpO1GoEhgb7SFKpIlh2+wXfAKd4KE7qhfAZewogs",
	"pnM6GMJJrK7jv13sQT8EMCF78lJgZpvx8m7M+Lt52Bh6X/TXisyPQ6W+x+kKD4aUU0qB3c101L0UW476",
	"VtKSf4QX4h8wgFPRI2u1a/cktJK4y8Tt6idZmjoIrGQIF+JruetoVX+FofiWwEha3GsYkZX7xW1BsvLC",
	"EeehHD1HwMmG3DwAncgOJ3C49FRkUhSqXE8UCuoiFJObhVuVhcU7G7cWl27fWbr7wZ8vLU5pAnz9kQqO",
	"ZbCSyDkSR7JoPSRjcd5SfztHgNf+hs+cQh9OtdDkBgzlk+fobrJSfCF6EsiPCIzgtcRs5ZhH7xf3RUxg",
	"F760+I7T4QuRimABYH7UZvYf1bM1/9E5cbUQQU/UfpLFgSTq/gyvYShTmFOJuvmAJ/ZDw6XGT8WeOBQ9",
	"WQHF7XkBAzhJjZvF1T/mzIXRsDZ+YA5AdJoBVGhQWMx1+Rz3xXflUdS5cbQUmeLNoypyvM7dK8/tcQ3t",
	"ptFgZn0L7bNzl14eiMZenlP9H8ExjOBXGCXtvE8nljVdGp1pswB4w0/y7YPE0cMQEfRYHKpTMwRUlO+N",
	"gPkQzjCXTj++e54G9lOyEV21xCAtRQ9g6gc1B5wg7J/LKHCkEjQMC/twBgPiH209NZqdLGbjDwqYTcOw",
	"bYeTMSYRxyZKBgWX3RK1nXuGbVqmrhhE5RI9ySUw5ooDeK3PimQUQ542VCxF42OmaLHzt0A62yGqykO0",
	"ScmiTWMsD7Fswhlm9kpQXtX+GxP0p9xNeyEO4Sxx7JUG8uf5i4icKYaPN3XdyfLkCecYZAh3CN+xPK3p",
	"y2OT8AP0xZ44EH8LnOilyjX84zx4je4Mx2jXRGcSKf4njpIxMzlU0wXkjBcYMmVOc5EJIlLXBF6ijDhE",
	"DlO0c6D+jncV5ERW/2QhK3eRBxT0Cplf9AQkNQsRPc3KMTeV7QCKQQW6mZyaxN8hDhLvCBSlFh3SUBn9",
	"pLzrl1C7ipGZOv9b8Kv2uWrcYEZr3C0iOZqpckDZZDA1RY+2w1wpO492QaTt0b9lhNF1E9HDGPgmeLqU",
	"I6fMBf2JrP00ZSVwgrwimsyiAWU5WgH7kSxiZutBGvGb7bwbtpPeEII56/RmhHlmeVdnm7OB0Kcec1X7",
	"1fwQFG4x+82I7MnJ0jTlw2mAKLstrrAtTQ9IgSXNC0e/2dF129FkUJrOpGR8M0wzvyqDYadqmvNUYvzG",
	"lMe7wUG/KiYEp+K02rQajHZLkTGL0TEfOVvS2EJH7bRtPGvJ3ujCdGLDJ1CXfFzKdV9OeMGhpgHVyFFE",
	"A3kPFVDJltH4nOme0qxiyljWAooqUs+IBuLwESrGYPTEyjV64g8wQB8Se5IqnCI3E4fwSmEx8sCR2Cc3",
	"pEfhr6EsSu+VCHoNOp4k8brIfBlnrNEe3YAo+5t2hSet8a2Z9dQ1kvIcELFPJGL15RvG7fLnMCQ3gt0X",
	"34leGUbwQhfZzsSRqqCkIhUM4FW4qI/mFwGroFFrMmYFjV9TQ1dxFEl2s11apXY2IYqnyhiI+tI1hnAM",
	"Q1XSV/5aCjHszErJuPvgrc72/yPNc18VeDPXnGbeqvKZVfhJrUAkzJWZFp9sqMs4anYTjaK6zb6s5/eh",
	"OU2zPkWHZXR4KTbB1R1UTBvJE5+jJL/VkQU3XRJ8M1X1IgZcNNpcUXTYJ6KHPoIxkajAKNV1Pk3g+N7X",
	"s99WkfrpVKbnaA6TRWVw/AM2ewlFfcQ0I2sJhflEmvbWJH6leR0o3LwT27d3tMhTIHXJMEnZEz6ZKSEj",
	"9mahSsX0FOtOvjT+Unz2qUhvsovyw7eAik8BYv+Seas8MPKPHiewa2kBEaOZnALIZ+bMAYpt3PWF5amN",
	"JRqZ36HKTSLSzWIk20w3FuXFPPnYA3/kbOW6ywp84T4PNf2VtolsxuJgwY5G7xI7rSZ8JJb+FUpUmEJ9",
	"IdH2rfdUf3KWUb27Fc612nvisETgVxye22NSqEUh27dazlO24fgfzOXD8MNg8PURshns6u0iYdOj/ZhY",
	"n8MAo/Bbhfi666nAtxfpXSLnOqvIjwcE3Vq3g4gD8W0sRc01aY/xFa/qf4g2wabXQ6PnqOGHiMkTo+mx",
	"4og84au5Gcx/0pdwl9wo2dGfOyZVkEa9JlK2HFWNZyrgbUViyY+huut36sAIXmWC7TsUTX5RvUF6cbok",
	"9zWcQR9+JaEK34XujR9OlZd1/Wu74/+URLFBJOj6ghocuhDp0wpd118khq6oI7juZvd/AQAA///iEtpM",
	"2UcAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
