// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ErrorResponseErrorCode.
const (
	INTERNALERROR   ErrorResponseErrorCode = "INTERNAL_ERROR"
	NOCANDIDATE     ErrorResponseErrorCode = "NO_CANDIDATE"
	NOTASSIGNED     ErrorResponseErrorCode = "NOT_ASSIGNED"
	NOTFOUND        ErrorResponseErrorCode = "NOT_FOUND"
	PREXISTS        ErrorResponseErrorCode = "PR_EXISTS"
	PRMERGED        ErrorResponseErrorCode = "PR_MERGED"
	TEAMEXISTS      ErrorResponseErrorCode = "TEAM_EXISTS"
	USERNOTACTIVE   ErrorResponseErrorCode = "USER_NOT_ACTIVE"
	VALIDATIONERROR ErrorResponseErrorCode = "VALIDATION_ERROR"
)

// Defines values for PullRequestStatus.
const (
	PullRequestStatusMERGED PullRequestStatus = "MERGED"
	PullRequestStatusOPEN   PullRequestStatus = "OPEN"
)

// Defines values for PullRequestShortStatus.
const (
	PullRequestShortStatusMERGED PullRequestShortStatus = "MERGED"
	PullRequestShortStatusOPEN   PullRequestShortStatus = "OPEN"
)

// CountResponse defines model for CountResponse.
type CountResponse struct {
	Count int `json:"count"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error struct {
		Code    ErrorResponseErrorCode `json:"code"`
		Message string                 `json:"message"`
	} `json:"error"`
}

// ErrorResponseErrorCode defines model for ErrorResponse.Error.Code.
type ErrorResponseErrorCode string

// PullRequest defines model for PullRequest.
type PullRequest struct {
	// AssignedReviewers user_id назначенных ревьюверов (0..2)
	AssignedReviewers []string          `json:"assigned_reviewers"`
	AuthorId          string            `json:"author_id"`
	CreatedAt         *time.Time        `json:"createdAt"`
	MergedAt          *time.Time        `json:"mergedAt"`
	PullRequestId     string            `json:"pull_request_id"`
	PullRequestName   string            `json:"pull_request_name"`
	Status            PullRequestStatus `json:"status"`
}

// PullRequestStatus defines model for PullRequest.Status.
type PullRequestStatus string

// PullRequestCreateRequest defines model for PullRequestCreateRequest.
type PullRequestCreateRequest struct {
	AuthorId        string `json:"author_id"`
	PullRequestName string `json:"pull_request_name"`
}

// PullRequestShort defines model for PullRequestShort.
type PullRequestShort struct {
	AuthorId        string                 `json:"author_id"`
	PullRequestId   string                 `json:"pull_request_id"`
	PullRequestName string                 `json:"pull_request_name"`
	Status          PullRequestShortStatus `json:"status"`
}

// PullRequestShortStatus defines model for PullRequestShort.Status.
type PullRequestShortStatus string

// StatItem defines model for StatItem.
type StatItem struct {
	ReviewCount *int64  `json:"review_count,omitempty"`
	UserId      *string `json:"user_id,omitempty"`
}

// StatsResponse defines model for StatsResponse.
type StatsResponse struct {
	ReviewStats *[]StatItem `json:"review_stats,omitempty"`
}

// Team defines model for Team.
type Team struct {
	Members  []TeamMember `json:"members"`
	TeamName string       `json:"team_name"`
}

// TeamDeactivateRequest defines model for TeamDeactivateRequest.
type TeamDeactivateRequest struct {
	TeamName string `json:"team_name"`
}

// TeamDeactivateResponse defines model for TeamDeactivateResponse.
type TeamDeactivateResponse struct {
	DeactivatedUsersCount  *int `json:"deactivated_users_count,omitempty"`
	ReassignedReviewsCount *int `json:"reassigned_reviews_count,omitempty"`
}

// TeamMember defines model for TeamMember.
type TeamMember struct {
	IsActive bool   `json:"is_active"`
	UserId   string `json:"user_id"`
	Username string `json:"username"`
}

// User defines model for User.
type User struct {
	IsActive bool   `json:"is_active"`
	TeamName string `json:"team_name"`
	UserId   string `json:"user_id"`
	Username string `json:"username"`
}

// UserAddRequest defines model for UserAddRequest.
type UserAddRequest struct {
	IsActive bool   `json:"is_active"`
	TeamName string `json:"team_name"`
	Username string `json:"username"`
}

// PullRequestIdParam defines model for PullRequestIdParam.
type PullRequestIdParam = string

// TeamNameParam defines model for TeamNameParam.
type TeamNameParam = string

// TeamNameQuery defines model for TeamNameQuery.
type TeamNameQuery = string

// UserIdParam defines model for UserIdParam.
type UserIdParam = string

// UserIdQuery defines model for UserIdQuery.
type UserIdQuery = string

// PostPullRequestAssignJSONBody defines parameters for PostPullRequestAssign.
type PostPullRequestAssignJSONBody struct {
	PullRequestId string `json:"pull_request_id"`
	UserId        string `json:"user_id"`
}

// PostPullRequestMergeJSONBody defines parameters for PostPullRequestMerge.
type PostPullRequestMergeJSONBody struct {
	PullRequestId string `json:"pull_request_id"`
}

// PostPullRequestReassignJSONBody defines parameters for PostPullRequestReassign.
type PostPullRequestReassignJSONBody struct {
	OldUserId     string `json:"old_user_id"`
	PullRequestId string `json:"pull_request_id"`
}

// PostTeamEditJSONBody defines parameters for PostTeamEdit.
type PostTeamEditJSONBody struct {
	NewTeamName string `json:"new_team_name"`
	OldTeamName string `json:"old_team_name"`
}

// GetTeamGetParams defines parameters for GetTeamGet.
type GetTeamGetParams struct {
	// TeamName Уникальное имя команды
	TeamName TeamNameQuery `form:"team_name" json:"team_name"`
}

// GetUsersGetReviewParams defines parameters for GetUsersGetReview.
type GetUsersGetReviewParams struct {
	// UserId Идентификатор пользователя
	UserId UserIdQuery `form:"user_id" json:"user_id"`
}

// PostUsersMoveToTeamJSONBody defines parameters for PostUsersMoveToTeam.
type PostUsersMoveToTeamJSONBody struct {
	NewTeamName string `json:"new_team_name"`
	UserId      string `json:"user_id"`
}

// PostUsersSetIsActiveJSONBody defines parameters for PostUsersSetIsActive.
type PostUsersSetIsActiveJSONBody struct {
	IsActive bool   `json:"is_active"`
	UserId   string `json:"user_id"`
}

// PostPullRequestAssignJSONRequestBody defines body for PostPullRequestAssign for application/json ContentType.
type PostPullRequestAssignJSONRequestBody PostPullRequestAssignJSONBody

// PostPullRequestCreateJSONRequestBody defines body for PostPullRequestCreate for application/json ContentType.
type PostPullRequestCreateJSONRequestBody = PullRequestCreateRequest

// PostPullRequestMergeJSONRequestBody defines body for PostPullRequestMerge for application/json ContentType.
type PostPullRequestMergeJSONRequestBody PostPullRequestMergeJSONBody

// PostPullRequestReassignJSONRequestBody defines body for PostPullRequestReassign for application/json ContentType.
type PostPullRequestReassignJSONRequestBody PostPullRequestReassignJSONBody

// PostTeamAddJSONRequestBody defines body for PostTeamAdd for application/json ContentType.
type PostTeamAddJSONRequestBody = Team

// PostTeamDeactivateJSONRequestBody defines body for PostTeamDeactivate for application/json ContentType.
type PostTeamDeactivateJSONRequestBody = TeamDeactivateRequest

// PostTeamEditJSONRequestBody defines body for PostTeamEdit for application/json ContentType.
type PostTeamEditJSONRequestBody PostTeamEditJSONBody

// PostUsersAddJSONRequestBody defines body for PostUsersAdd for application/json ContentType.
type PostUsersAddJSONRequestBody = UserAddRequest

// PostUsersEditJSONRequestBody defines body for PostUsersEdit for application/json ContentType.
type PostUsersEditJSONRequestBody = User

// PostUsersMoveToTeamJSONRequestBody defines body for PostUsersMoveToTeam for application/json ContentType.
type PostUsersMoveToTeamJSONRequestBody PostUsersMoveToTeamJSONBody

// PostUsersSetIsActiveJSONRequestBody defines body for PostUsersSetIsActive for application/json ContentType.
type PostUsersSetIsActiveJSONRequestBody PostUsersSetIsActiveJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Check service health
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// Назначить ревьювера на PR
	// (POST /pullRequest/assign)
	PostPullRequestAssign(w http.ResponseWriter, r *http.Request)
	// Создать PR и автоматически назначить до 2 ревьюверов из команды автора
	// (POST /pullRequest/create)
	PostPullRequestCreate(w http.ResponseWriter, r *http.Request)
	// Получить информацию о PR по ID
	// (GET /pullRequest/get/{pull_request_id})
	GetPullRequestGetPullRequestId(w http.ResponseWriter, r *http.Request, pullRequestId PullRequestIdParam)
	// Пометить PR как MERGED (идемпотентная операция)
	// (POST /pullRequest/merge)
	PostPullRequestMerge(w http.ResponseWriter, r *http.Request)
	// Получить список открытых PR без ревьюверов
	// (GET /pullRequest/open-without-reviewers)
	GetPullRequestOpenWithoutReviewers(w http.ResponseWriter, r *http.Request)
	// Переназначить конкретного ревьювера на другого из его команды
	// (POST /pullRequest/reassign)
	PostPullRequestReassign(w http.ResponseWriter, r *http.Request)
	// Получить статистику по ревью
	// (GET /stats)
	GetStats(w http.ResponseWriter, r *http.Request)
	// Получить количество закрытых PR у команды
	// (GET /stats/team/{team_name}/merged-review-count)
	GetStatsTeamTeamNameMergedReviewCount(w http.ResponseWriter, r *http.Request, teamName TeamNameParam)
	// Получить количество назначенных OPEN PR у команды
	// (GET /stats/team/{team_name}/open-review-count)
	GetStatsTeamTeamNameOpenReviewCount(w http.ResponseWriter, r *http.Request, teamName TeamNameParam)
	// Получить количество закрытых PR у пользователя
	// (GET /stats/user/{user_id}/merged-review-count)
	GetStatsUserUserIdMergedReviewCount(w http.ResponseWriter, r *http.Request, userId UserIdParam)
	// Получить количество назначенных OPEN PR у пользователя
	// (GET /stats/user/{user_id}/open-review-count)
	GetStatsUserUserIdOpenReviewCount(w http.ResponseWriter, r *http.Request, userId UserIdParam)
	// Создать команду с участниками (создаёт/обновляет пользователей)
	// (POST /team/add)
	PostTeamAdd(w http.ResponseWriter, r *http.Request)
	// Массово деактивировать команду и переназначить ревью
	// (POST /team/deactivate)
	PostTeamDeactivate(w http.ResponseWriter, r *http.Request)
	// Изменить имя команды
	// (POST /team/edit)
	PostTeamEdit(w http.ResponseWriter, r *http.Request)
	// Получить команду с участниками
	// (GET /team/get)
	GetTeamGet(w http.ResponseWriter, r *http.Request, params GetTeamGetParams)
	// Добавить пользователя
	// (POST /users/add)
	PostUsersAdd(w http.ResponseWriter, r *http.Request)
	// Изменить пользователя
	// (POST /users/edit)
	PostUsersEdit(w http.ResponseWriter, r *http.Request)
	// Получить PR'ы, где пользователь назначен ревьювером
	// (GET /users/getReview)
	GetUsersGetReview(w http.ResponseWriter, r *http.Request, params GetUsersGetReviewParams)
	// Переместить пользователя в другую команду
	// (POST /users/moveToTeam)
	PostUsersMoveToTeam(w http.ResponseWriter, r *http.Request)
	// Установить флаг активности пользователя
	// (POST /users/setIsActive)
	PostUsersSetIsActive(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Check service health
// (GET /health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Назначить ревьювера на PR
// (POST /pullRequest/assign)
func (_ Unimplemented) PostPullRequestAssign(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Создать PR и автоматически назначить до 2 ревьюверов из команды автора
// (POST /pullRequest/create)
func (_ Unimplemented) PostPullRequestCreate(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получить информацию о PR по ID
// (GET /pullRequest/get/{pull_request_id})
func (_ Unimplemented) GetPullRequestGetPullRequestId(w http.ResponseWriter, r *http.Request, pullRequestId PullRequestIdParam) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Пометить PR как MERGED (идемпотентная операция)
// (POST /pullRequest/merge)
func (_ Unimplemented) PostPullRequestMerge(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получить список открытых PR без ревьюверов
// (GET /pullRequest/open-without-reviewers)
func (_ Unimplemented) GetPullRequestOpenWithoutReviewers(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Переназначить конкретного ревьювера на другого из его команды
// (POST /pullRequest/reassign)
func (_ Unimplemented) PostPullRequestReassign(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получить статистику по ревью
// (GET /stats)
func (_ Unimplemented) GetStats(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получить количество закрытых PR у команды
// (GET /stats/team/{team_name}/merged-review-count)
func (_ Unimplemented) GetStatsTeamTeamNameMergedReviewCount(w http.ResponseWriter, r *http.Request, teamName TeamNameParam) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получить количество назначенных OPEN PR у команды
// (GET /stats/team/{team_name}/open-review-count)
func (_ Unimplemented) GetStatsTeamTeamNameOpenReviewCount(w http.ResponseWriter, r *http.Request, teamName TeamNameParam) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получить количество закрытых PR у пользователя
// (GET /stats/user/{user_id}/merged-review-count)
func (_ Unimplemented) GetStatsUserUserIdMergedReviewCount(w http.ResponseWriter, r *http.Request, userId UserIdParam) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получить количество назначенных OPEN PR у пользователя
// (GET /stats/user/{user_id}/open-review-count)
func (_ Unimplemented) GetStatsUserUserIdOpenReviewCount(w http.ResponseWriter, r *http.Request, userId UserIdParam) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Создать команду с участниками (создаёт/обновляет пользователей)
// (POST /team/add)
func (_ Unimplemented) PostTeamAdd(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Массово деактивировать команду и переназначить ревью
// (POST /team/deactivate)
func (_ Unimplemented) PostTeamDeactivate(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Изменить имя команды
// (POST /team/edit)
func (_ Unimplemented) PostTeamEdit(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получить команду с участниками
// (GET /team/get)
func (_ Unimplemented) GetTeamGet(w http.ResponseWriter, r *http.Request, params GetTeamGetParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Добавить пользователя
// (POST /users/add)
func (_ Unimplemented) PostUsersAdd(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Изменить пользователя
// (POST /users/edit)
func (_ Unimplemented) PostUsersEdit(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получить PR'ы, где пользователь назначен ревьювером
// (GET /users/getReview)
func (_ Unimplemented) GetUsersGetReview(w http.ResponseWriter, r *http.Request, params GetUsersGetReviewParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Переместить пользователя в другую команду
// (POST /users/moveToTeam)
func (_ Unimplemented) PostUsersMoveToTeam(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Установить флаг активности пользователя
// (POST /users/setIsActive)
func (_ Unimplemented) PostUsersSetIsActive(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostPullRequestAssign operation middleware
func (siw *ServerInterfaceWrapper) PostPullRequestAssign(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostPullRequestAssign(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostPullRequestCreate operation middleware
func (siw *ServerInterfaceWrapper) PostPullRequestCreate(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostPullRequestCreate(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPullRequestGetPullRequestId operation middleware
func (siw *ServerInterfaceWrapper) GetPullRequestGetPullRequestId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "pull_request_id" -------------
	var pullRequestId PullRequestIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "pull_request_id", chi.URLParam(r, "pull_request_id"), &pullRequestId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pull_request_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPullRequestGetPullRequestId(w, r, pullRequestId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostPullRequestMerge operation middleware
func (siw *ServerInterfaceWrapper) PostPullRequestMerge(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostPullRequestMerge(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPullRequestOpenWithoutReviewers operation middleware
func (siw *ServerInterfaceWrapper) GetPullRequestOpenWithoutReviewers(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPullRequestOpenWithoutReviewers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostPullRequestReassign operation middleware
func (siw *ServerInterfaceWrapper) PostPullRequestReassign(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostPullRequestReassign(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStats operation middleware
func (siw *ServerInterfaceWrapper) GetStats(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStats(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStatsTeamTeamNameMergedReviewCount operation middleware
func (siw *ServerInterfaceWrapper) GetStatsTeamTeamNameMergedReviewCount(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "team_name" -------------
	var teamName TeamNameParam

	err = runtime.BindStyledParameterWithOptions("simple", "team_name", chi.URLParam(r, "team_name"), &teamName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "team_name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStatsTeamTeamNameMergedReviewCount(w, r, teamName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStatsTeamTeamNameOpenReviewCount operation middleware
func (siw *ServerInterfaceWrapper) GetStatsTeamTeamNameOpenReviewCount(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "team_name" -------------
	var teamName TeamNameParam

	err = runtime.BindStyledParameterWithOptions("simple", "team_name", chi.URLParam(r, "team_name"), &teamName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "team_name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStatsTeamTeamNameOpenReviewCount(w, r, teamName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStatsUserUserIdMergedReviewCount operation middleware
func (siw *ServerInterfaceWrapper) GetStatsUserUserIdMergedReviewCount(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "user_id" -------------
	var userId UserIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", chi.URLParam(r, "user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStatsUserUserIdMergedReviewCount(w, r, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStatsUserUserIdOpenReviewCount operation middleware
func (siw *ServerInterfaceWrapper) GetStatsUserUserIdOpenReviewCount(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "user_id" -------------
	var userId UserIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", chi.URLParam(r, "user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStatsUserUserIdOpenReviewCount(w, r, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostTeamAdd operation middleware
func (siw *ServerInterfaceWrapper) PostTeamAdd(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostTeamAdd(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostTeamDeactivate operation middleware
func (siw *ServerInterfaceWrapper) PostTeamDeactivate(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostTeamDeactivate(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostTeamEdit operation middleware
func (siw *ServerInterfaceWrapper) PostTeamEdit(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostTeamEdit(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTeamGet operation middleware
func (siw *ServerInterfaceWrapper) GetTeamGet(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTeamGetParams

	// ------------- Required query parameter "team_name" -------------

	if paramValue := r.URL.Query().Get("team_name"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "team_name"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "team_name", r.URL.Query(), &params.TeamName)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "team_name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTeamGet(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostUsersAdd operation middleware
func (siw *ServerInterfaceWrapper) PostUsersAdd(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostUsersAdd(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostUsersEdit operation middleware
func (siw *ServerInterfaceWrapper) PostUsersEdit(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostUsersEdit(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUsersGetReview operation middleware
func (siw *ServerInterfaceWrapper) GetUsersGetReview(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUsersGetReviewParams

	// ------------- Required query parameter "user_id" -------------

	if paramValue := r.URL.Query().Get("user_id"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "user_id"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "user_id", r.URL.Query(), &params.UserId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUsersGetReview(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostUsersMoveToTeam operation middleware
func (siw *ServerInterfaceWrapper) PostUsersMoveToTeam(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostUsersMoveToTeam(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostUsersSetIsActive operation middleware
func (siw *ServerInterfaceWrapper) PostUsersSetIsActive(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostUsersSetIsActive(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/pullRequest/assign", wrapper.PostPullRequestAssign)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/pullRequest/create", wrapper.PostPullRequestCreate)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/pullRequest/get/{pull_request_id}", wrapper.GetPullRequestGetPullRequestId)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/pullRequest/merge", wrapper.PostPullRequestMerge)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/pullRequest/open-without-reviewers", wrapper.GetPullRequestOpenWithoutReviewers)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/pullRequest/reassign", wrapper.PostPullRequestReassign)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/stats", wrapper.GetStats)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/stats/team/{team_name}/merged-review-count", wrapper.GetStatsTeamTeamNameMergedReviewCount)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/stats/team/{team_name}/open-review-count", wrapper.GetStatsTeamTeamNameOpenReviewCount)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/stats/user/{user_id}/merged-review-count", wrapper.GetStatsUserUserIdMergedReviewCount)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/stats/user/{user_id}/open-review-count", wrapper.GetStatsUserUserIdOpenReviewCount)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/team/add", wrapper.PostTeamAdd)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/team/deactivate", wrapper.PostTeamDeactivate)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/team/edit", wrapper.PostTeamEdit)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/team/get", wrapper.GetTeamGet)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/users/add", wrapper.PostUsersAdd)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/users/edit", wrapper.PostUsersEdit)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users/getReview", wrapper.GetUsersGetReview)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/users/moveToTeam", wrapper.PostUsersMoveToTeam)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/users/setIsActive", wrapper.PostUsersSetIsActive)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xcbW8bxxH+K4ttgTgAZcqyHSD6xtiKKyCWVYpOixoCceKtxUvIO+bu6MQQCEhU2rRV",
	"EDVAPwRFkzTIH6AVs6JlkfoLs/+omN29N94Ljy+yLDRfDJHc252dnXlmntk579Ga1WxZJjNdh67u0ZZm",
	"a03mMlt82mw3GmX2WZs57rq+iT/htzpzarbRcg3LpKsUvoOX0Ich78KAfwkDOIMe78KI7xN8nKjnaYEa",
	"OLyluXVaoKbWZPip3WhUbTmiaui0QPGDYTOdrrp2mxWoU6uzpobLus9b+Ijj2oa5SzudAq0wrbmhNVma",
	"ZD/DUMoDr/nXMIQR9AkM4JwfEziDEZxDD4bwkh8lC+cyrVkVf88m1u/bzH6+CLE+ExPNLddjh9mzHCNc",
	"wEiIegojOBFf9+E1P07WWtth9vRHKWVL09jsso2pbhbhOt6PwiXuWW3TLTOnZZkOEx5jWy1muwYTP9fw",
	"59AshumyXWaLPQZLPlHjtgveOGvnE1ZzaadA12zbssMLsC+0Zqsh/8Tf5DI6PrXxqFL98NHjjfu0QJvM",
	"cbRd/NZmjtW2a4yYlkueWm1TF8tHBfWnGpdflyuZ7SbKWVkrPayu/XF9q7JFC3SzHPn74Vr5wRqujXKU",
	"trbWH2yoj9V7pY376/dLlTX1qyflx6WP8Ov1RxvVtXL5UZkW6OOttXJVzHCvsv4xPrC+UVkrb5Q+UkMC",
	"LXlnEtptkjFFFa2zkHbiGh8bL/WSdDAhMIzrTXMcY9dketVmzwz2ucLPqBkr4yMwhB6c4r/8KzRrGPIj",
	"/mfC96EPJ/xr/g2cQJ/vo0GTG8s3b668i9bssqaTsF1fUM22tef4WWu7dUtYedLoms00l+klsYenlt3U",
	"XLpKdc1lS64hIMVsNxraDhqc9IwE3du7880wDvtJgkbGSPdNGOW4mtt2whb7aHNtgxaoss247YyddzwC",
	"xRcO69RfspB05hPs5p5QfroRZZ5cHoVkbS62lQnCbtUtez4hr+nJJully9XcdZc14/qQh1/1gd/3CMN0",
	"37tDC7FIUPCjUOL5JS7tpEcctT7KLj77QPFbmz2lq/Q3xSDDK6pAVvS3E8OPJAkwoYkv3GTNHYVzudbE",
	"WR6KZ5JQK0hqJlp1OP/xhNhOEfs+02qu8SzL62ZaOc96aSem+2P0KpqCU03NGnD5MZjJGJ12dkrrMUEM",
	"pyokYVKqp1q74Y5h9o5lNZhmZlut/C2fCoMMzH+mEBIkSa+YG04QPi5t1qle6l7C1jl5XyVdTzXMuXeY",
	"fxdTyo5TGOZTS0xuuBjp6WaZlFUcJCVhsk1mumSL2c+MGiM3KsxxSUVzPi2QD7VGg6wsr9zFxOYZsx2Z",
	"H926uXxzGWW3WszUWgZdpbdvLt+8jcituXWhk2KdaQ23jn/uMqEz1JiGGda6TlfpA+b+To7ATUoPFA+u",
	"LC/HMzJPOMMhcl4JgE672dSQiNB7dVb7lDhqWN2b2dV2HVSdWmobHyq2gtBZlD4rjtRyEsTctBw3FGql",
	"vhQrYY77gaU/l9m46TLp61qr1TBqYobiJ44l5g44S9Rw8gThzBiUHUa9R5PtIkqsOsnHkHtjWQElnJCL",
	"pcdY43+i+XQs70Y13Fm+szB5oswtQaLNMvL81zBIo61fo4x9KegryXmlkO/nEFLxRBWbMUUXovu2DN/L",
	"NeCUH0d10eNduXSPyOSKbCIxe6Y12om0M0z9AtpZ00wknNL0iWUSKQTOJXRhWm7Jh7OQWD9mqAJ6cIas",
	"H08QhlkyxVlkIBkaLPq4EE+K0Anx+rnPFb6HHt/nh/yvgs4N8AhfikJOwO7ggu9DD07QAOIMcMCPx5AH",
	"5/SHDMQBxQhiT56ZOCwPkkJO4SQAk6R/uYFJEpapgSlUsgjRBdq+lZiEr9KSrhOHaXatTnOfSiqtyoVC",
	"t6bbRctOI/lPaHsFMfE2wmFssyG2TTHgLd1aXlq5U7m1snr7zurd9/5Ew2waaXMCg6Ite+nW8nIO3QWk",
	"SXKlqImPxQh7OnhNxPoYvPEDGMEpvITeFcAr/ANOZFmwGK6jSjeJoio/mhpXU4DQr4cFcLNZJoZOtIbN",
	"NP05YV8Y6IoLhBvU8yH8F/qEH/BD/jfo8wPehRN+CH3eHceRn7wTERgiQhBBIEJNoYpEUfUrnAPO8Kdh",
	"DHcQy8hKcn0KBnA6VrX2Z0eEyo9Mu8wt7o0ZfycrzwvNF/20Lrh+6CLjSbLCgyHFhIuOzvYVpi4/wAv+",
	"d+hj8BPx8woSlXgiErUrGbYPAysZwJB/KU4dreovMODfEBgJi7uAEVm/n98WBCbmDlIPxeg5YlQ65GYB",
	"6MQke0IifXnp8wICVxCV0uLWYuKUyiPffKSCExGsBHKO+LFI2wbEE+ct9bdzBHjlb/jMGebHXs5+Awbi",
	"yXN0N5FFD3lXAPkxgRFcyJRROObxu/l9Ecn40ueGW7fa7lLkdiMHMD9qMfMP8tmy/+icuJqr2BirY8cL",
	"nXHU/QkuYCBSmDPJWjIBjx+EhguNn/F9fsS7It/H43kBfThNjJv51e/V/3KjYdl7YA5AtBoBVChQWMl0",
	"+Qz3xbmyym1z42ghssTVo+ptRNW7iai6yNwe99BqaDWmV3fQPtt36eJAdGzyjJtM5Owj+AVGCfSUTryi",
	"sWl0pe0c4A0/itn7cRKNCHrCj2RxRZQPhjD6v67yiAoEP5YJGoaFA3gNfeJXb2Yr8XiYlFjkuaeZuqGr",
	"IkNULt4VXAJjLj+EC68ycqZ42kCyFIWPqaKNdRcE0pmWqu4QZVKiAF3z5CGGSVyGmb1XjVL+O0U9isAL",
	"fpRQwEkC+fPsTUQ6JsLNG6qG7tWrlJDEtYhbNxyl6assXl2k+V+8iJXkqoouIGccYsgUOc0wFURkjQte",
	"oow4RAyTtLMv/x7vmcqIrP4taVruIi5b6SUyv+htbmIWwruKlR+I0ucZbv8iopvJqcn4HPwwNkegKLnp",
	"kIaK6CfFPf86qCMZma7yvyX/BjJTjRWmNb1eOMHRdJkDihaqqSl6tNnvUtl5tMcr6Yz+JSKMqpvwLsbA",
	"q+DpQo6MMhf0JrL2s4SdwKmou0eSWTSgNEfLYT+CRcxsPUgjfrWd62E7yc1tmLNOb0aYZxb3VLY5Gwg9",
	"dpgtm0vnh6BwA+2vRmROTpamKR9OA0TpTb+5bWl6QAosaV44+tWO3rQdTQal6UxKxDdN17OrMhh2Sro+",
	"TyXGb7J7she0bMhiQtDhQ0sNo8ZopxAZsxId84G1I4wt1DZEW9rzpnjzIzedqPgEasE3rK7qMQxvONQA",
	"JZvS8mgg66EcKtnRap8y1TGfVkzxZM2hqDz1jGggDl+hYgxGT1x+g574PfTRh/i+oApnyM34EbySWIw8",
	"cMQPyA3hUfhpIIrS+wWCXoOOJ0i8KjIv4o41+gZCQJT9Q7vEm9bxo5n11jWS8hwSfkAEYvXEDN7LQOcw",
	"IDeC0+ff8m4RRvBCFdle82NZQUlEKujDq3BRH80vAlZB0+lkzAqaWOdoSZvkHPHO3DfcPpbSrpsjVX4Z",
	"aUwayJK+9NdCiGGnVkq87oO3Otv/tzDPA1ngTd1zknnLymda4SexAhEzV6Yb7mRDXcNRi+qaNNnn1eye",
	"WquhV6foFo8OL4wtcNXdk0Ekj71sF38TURTcVEnwaqrqeQw4b7S5pOhwQHgXfQRjIpGBUajrfJrA8Z2v",
	"Z7+tIvHF0FTPURwmjcrg+Ads9hKKfEVzRtYSCvOxNO2tSfwK8zpQuHln7NyuaZEnR+qSYpLi/ZbJTAkZ",
	"sTMLVcqnp7E3LRbGX/KvPhXpjXdRvv8WUPEpQOyfIm8VF0b+1eMEdi0sIGI0k1MA8cycOUC+g3tzYXlq",
	"Y4lG5mtUuYlFulmMZJepxqKsmCcee+CPnK1ct6jAF+7zkMtfapvI9lgczNnR6Cyw02qKl42CN+qiwuTq",
	"C4m2b70j+5PTjOr6Vjg3y+/wowKBX3B4Zo9JrhaFdN9qWs9YxfJf/s2G4YfB4DdHyGawq7eLhE2P9h6x",
	"Poc+RuG3CvFV11OOdy+Su0TOVVaRHQ8IurVqB+GH/JuxFDXTpB3mrjvBW2gTbHorNHqOGn6ImDzVGg7L",
	"j8gT3gCewfwnvdW74EbJtnp1O66CJOo1kbJlqMpbKYe35YklP4Tqrt/KCyN4lQq21yia/Cx7g9TmVEnu",
	"S3gNPfiFhCp8Q9UbP5gqL+v43+15/+WSZINI0NUXcnDoi0ifVuh79XZ16Bt5BdfZ7vwvAAD//1lPpOO3",
	"TAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
