// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package models

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type PrStatus string

const (
	PrStatusOPEN   PrStatus = "OPEN"
	PrStatusMERGED PrStatus = "MERGED"
)

func (e *PrStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PrStatus(s)
	case string:
		*e = PrStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PrStatus: %T", src)
	}
	return nil
}

type NullPrStatus struct {
	PrStatus PrStatus
	Valid    bool // Valid is true if PrStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPrStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PrStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PrStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPrStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PrStatus), nil
}

type PullRequest struct {
	PrID      string
	PrName    string
	AuthorID  string
	Status    PrStatus
	CreatedAt pgtype.Timestamptz
	MergedAt  pgtype.Timestamptz
}

type ReviewAssignment struct {
	PrID   string
	UserID string
}

type Team struct {
	TeamID   int32
	TeamName string
	IsActive bool
}

type User struct {
	UserID    string
	Username  string
	TeamID    int32
	IsActive  bool
	CreatedAt pgtype.Timestamptz
}
