// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package models

import (
	"context"
)

type Querier interface {
	ActivateTeam(ctx context.Context, teamID int32) (Team, error)
	AddReviewerToPR(ctx context.Context, arg AddReviewerToPRParams) error
	CountMergedReviewsByTeam(ctx context.Context, teamID int32) (int64, error)
	CountMergedReviewsByUser(ctx context.Context, userID string) (int64, error)
	CountOpenReviewsByTeam(ctx context.Context, teamID int32) (int64, error)
	CountOpenReviewsByUser(ctx context.Context, userID string) (int64, error)
	CountPRs(ctx context.Context) (int64, error)
	CountTeams(ctx context.Context) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreatePR(ctx context.Context, arg CreatePRParams) (PullRequest, error)
	CreateTeam(ctx context.Context, teamName string) (Team, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeactivateTeam(ctx context.Context, teamID int32) (Team, error)
	DeactivateUsersByTeam(ctx context.Context, teamID int32) ([]string, error)
	FindReplacementCandidates(ctx context.Context, arg FindReplacementCandidatesParams) ([]User, error)
	GetActiveUsersFromTeamExcluding(ctx context.Context, arg GetActiveUsersFromTeamExcludingParams) ([]User, error)
	GetAuthorTeamByPR(ctx context.Context, prID string) (Team, error)
	GetOpenPRsWithoutReviewers(ctx context.Context) ([]PullRequest, error)
	// Находим все ОТКРЫТЫЕ ревью для списка пользователей
	GetOpenReviewsForUsers(ctx context.Context, dollar_1 []string) ([]GetOpenReviewsForUsersRow, error)
	GetPRByID(ctx context.Context, prID string) (PullRequest, error)
	GetPRsForReviewer(ctx context.Context, userID string) ([]GetPRsForReviewerRow, error)
	GetReviewStats(ctx context.Context) ([]GetReviewStatsRow, error)
	GetReviewersForPR(ctx context.Context, prID string) ([]User, error)
	GetTeamByID(ctx context.Context, teamID int32) (Team, error)
	GetTeamByName(ctx context.Context, teamName string) (Team, error)
	GetTeamMembers(ctx context.Context, teamID int32) ([]User, error)
	GetUserWithTeam(ctx context.Context, userID string) (GetUserWithTeamRow, error)
	GetUsersByIDs(ctx context.Context, dollar_1 []string) ([]User, error)
	ListPRs(ctx context.Context) ([]PullRequest, error)
	ListTeams(ctx context.Context) ([]Team, error)
	ListUsers(ctx context.Context) ([]User, error)
	MergePR(ctx context.Context, prID string) (PullRequest, error)
	MoveUserToTeam(ctx context.Context, arg MoveUserToTeamParams) (User, error)
	RemoveAllReviewersFromPR(ctx context.Context, prID string) error
	RemoveReviewerFromPR(ctx context.Context, arg RemoveReviewerFromPRParams) error
	SetUserActiveStatus(ctx context.Context, arg SetUserActiveStatusParams) (User, error)
	UpdateTeamName(ctx context.Context, arg UpdateTeamNameParams) (Team, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
