// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: team.sql

package models

import (
	"context"
)

const activateTeam = `-- name: ActivateTeam :one
UPDATE teams
SET is_active = true
WHERE team_id = $1
RETURNING team_id, team_name, is_active
`

func (q *Queries) ActivateTeam(ctx context.Context, teamID int32) (Team, error) {
	row := q.db.QueryRow(ctx, activateTeam, teamID)
	var i Team
	err := row.Scan(&i.TeamID, &i.TeamName, &i.IsActive)
	return i, err
}

const countTeams = `-- name: CountTeams :one
SELECT count(*) FROM teams
`

func (q *Queries) CountTeams(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTeams)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (team_name)
VALUES ($1)
RETURNING team_id, team_name, is_active
`

func (q *Queries) CreateTeam(ctx context.Context, teamName string) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam, teamName)
	var i Team
	err := row.Scan(&i.TeamID, &i.TeamName, &i.IsActive)
	return i, err
}

const deactivateTeam = `-- name: DeactivateTeam :one
UPDATE teams
SET is_active = false
WHERE team_id = $1
RETURNING team_id, team_name, is_active
`

func (q *Queries) DeactivateTeam(ctx context.Context, teamID int32) (Team, error) {
	row := q.db.QueryRow(ctx, deactivateTeam, teamID)
	var i Team
	err := row.Scan(&i.TeamID, &i.TeamName, &i.IsActive)
	return i, err
}

const getTeamByID = `-- name: GetTeamByID :one
SELECT team_id, team_name, is_active FROM teams
WHERE team_id = $1
`

func (q *Queries) GetTeamByID(ctx context.Context, teamID int32) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamByID, teamID)
	var i Team
	err := row.Scan(&i.TeamID, &i.TeamName, &i.IsActive)
	return i, err
}

const getTeamByName = `-- name: GetTeamByName :one
SELECT team_id, team_name, is_active FROM teams
WHERE team_name = $1
`

func (q *Queries) GetTeamByName(ctx context.Context, teamName string) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamByName, teamName)
	var i Team
	err := row.Scan(&i.TeamID, &i.TeamName, &i.IsActive)
	return i, err
}

const listTeams = `-- name: ListTeams :many
SELECT team_id, team_name, is_active FROM teams
`

func (q *Queries) ListTeams(ctx context.Context) ([]Team, error) {
	rows, err := q.db.Query(ctx, listTeams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Team
	for rows.Next() {
		var i Team
		if err := rows.Scan(&i.TeamID, &i.TeamName, &i.IsActive); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTeamName = `-- name: UpdateTeamName :one
UPDATE teams
SET team_name = $2
WHERE team_id = $1
RETURNING team_id, team_name, is_active
`

type UpdateTeamNameParams struct {
	TeamID   int32
	TeamName string
}

func (q *Queries) UpdateTeamName(ctx context.Context, arg UpdateTeamNameParams) (Team, error) {
	row := q.db.QueryRow(ctx, updateTeamName, arg.TeamID, arg.TeamName)
	var i Team
	err := row.Scan(&i.TeamID, &i.TeamName, &i.IsActive)
	return i, err
}
