// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package models

import (
	"context"
)

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (user_id, username, team_id, is_active)
VALUES ($1, $2, $3, $4)
RETURNING user_id, username, team_id, is_active, created_at
`

type CreateUserParams struct {
	UserID   string
	Username string
	TeamID   int32
	IsActive bool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.UserID,
		arg.Username,
		arg.TeamID,
		arg.IsActive,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.TeamID,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const deactivateUsersByTeam = `-- name: DeactivateUsersByTeam :many
UPDATE users
SET is_active = false
WHERE team_id = $1
  AND is_active = true
RETURNING user_id
`

func (q *Queries) DeactivateUsersByTeam(ctx context.Context, teamID int32) ([]string, error) {
	rows, err := q.db.Query(ctx, deactivateUsersByTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var user_id string
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveUsersFromTeamExcluding = `-- name: GetActiveUsersFromTeamExcluding :many
SELECT user_id, username, team_id, is_active, created_at
FROM users
WHERE team_id = $1
  AND is_active = true
  AND user_id != ALL ($2::varchar[])
`

type GetActiveUsersFromTeamExcludingParams struct {
	TeamID  int32
	Column2 []string
}

func (q *Queries) GetActiveUsersFromTeamExcluding(ctx context.Context, arg GetActiveUsersFromTeamExcludingParams) ([]User, error) {
	rows, err := q.db.Query(ctx, getActiveUsersFromTeamExcluding, arg.TeamID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.TeamID,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTeamMembers = `-- name: GetTeamMembers :many
SELECT user_id, username, team_id, is_active, created_at FROM users
WHERE team_id = $1
`

func (q *Queries) GetTeamMembers(ctx context.Context, teamID int32) ([]User, error) {
	rows, err := q.db.Query(ctx, getTeamMembers, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.TeamID,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserWithTeam = `-- name: GetUserWithTeam :one
SELECT u.user_id, u.username, u.is_active, t.team_id, t.team_name, t.is_active as team_is_active
FROM users u
JOIN teams t ON u.team_id = t.team_id
WHERE u.user_id = $1
`

type GetUserWithTeamRow struct {
	UserID       string
	Username     string
	IsActive     bool
	TeamID       int32
	TeamName     string
	TeamIsActive bool
}

func (q *Queries) GetUserWithTeam(ctx context.Context, userID string) (GetUserWithTeamRow, error) {
	row := q.db.QueryRow(ctx, getUserWithTeam, userID)
	var i GetUserWithTeamRow
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.IsActive,
		&i.TeamID,
		&i.TeamName,
		&i.TeamIsActive,
	)
	return i, err
}

const getUsersByIDs = `-- name: GetUsersByIDs :many
SELECT user_id, username, team_id, is_active, created_at FROM users
WHERE user_id = ANY($1::varchar[])
`

func (q *Queries) GetUsersByIDs(ctx context.Context, dollar_1 []string) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsersByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.TeamID,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT user_id, username, team_id, is_active, created_at FROM users
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.TeamID,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveUserToTeam = `-- name: MoveUserToTeam :one
UPDATE users
SET team_id = $2
WHERE user_id = $1
RETURNING user_id, username, team_id, is_active, created_at
`

type MoveUserToTeamParams struct {
	UserID string
	TeamID int32
}

func (q *Queries) MoveUserToTeam(ctx context.Context, arg MoveUserToTeamParams) (User, error) {
	row := q.db.QueryRow(ctx, moveUserToTeam, arg.UserID, arg.TeamID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.TeamID,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const setUserActiveStatus = `-- name: SetUserActiveStatus :one
UPDATE users
SET is_active = $2
WHERE user_id = $1
RETURNING user_id, username, team_id, is_active, created_at
`

type SetUserActiveStatusParams struct {
	UserID   string
	IsActive bool
}

func (q *Queries) SetUserActiveStatus(ctx context.Context, arg SetUserActiveStatusParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserActiveStatus, arg.UserID, arg.IsActive)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.TeamID,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET username = $2,
    team_id = $3,
    is_active = $4
WHERE user_id = $1
RETURNING user_id, username, team_id, is_active, created_at
`

type UpdateUserParams struct {
	UserID   string
	Username string
	TeamID   int32
	IsActive bool
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.UserID,
		arg.Username,
		arg.TeamID,
		arg.IsActive,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.TeamID,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}
